solarwinds/swi-k8s-opentelemetry-collector

deploy/k8s/manifest.yaml
This metric is indicating whether it is possible to schedule something on the node (useful for Healthscore)
=> NH-9823: Adding metric 'kube_node_spec_unschedulable'

deploy/k8s/manifest.yaml, src/processor/swmetricstransformprocessor/factory.go
* `k8s.container.status` - indicating status of the container
* **approach**: combining 1 value datapoints of `kube_pod_container_status_waiting`, `kube_pod_container_status_running` and `kube_pod_container_status_terminated` metrics into single metric, and adding labels indicating the status value
* `k8s.container.ready` - indicating readyness of the container
* **approach**: split `kube_pod_container_status_ready` into two metrics, one with datapoints indicating true, other indicating false values. Then combine them back which adds labels on datapoints based on its value
=> NH-9828: Adding container status metrics

deploy/k8s/manifest.yaml, src/processor/swmetricstransformprocessor/config.go, src/processor/swmetricstransformprocessor/config_test.go, src/processor/swmetricstransformprocessor/factory.go, src/processor/swmetricstransformprocessor/operation_filter_datapoints.go, src/processor/swmetricstransformprocessor/processor_testcases_test.go, src/processor/swmetricstransformprocessor/testdata/config_full.yaml
Adding support for Include\Exclude of data point values in filter datapoints action in order to be able to exclude 0 values from metrics that should not return 0 data points at all.
=> NH-20269 Support Include\Exclude in filter datapoints action

.github/workflows/buildAndDeploy.yml
Getting rid of AWS authorization and ECR push. Image will now be published just to Docker hub
=> NH-9828: Reworking image publishing

deploy/k8s/manifest.yaml
Adding new cluster metrics in order to show them on the new Kubernetes Summary page
- k8s.cluster.nodes.ready
- k8s.cluster.spec.memory.requests
- k8s.cluster.spec.cpu.requests
- k8s.cluster.pods.running
=> NH-21059: Aggregate new cluster metrics

deploy/k8s/manifest.yaml
Added metrics:
* `k8s.apiserver.request.successrate` - success rate of apiserver requests
* `k8s.cluster.nodes.ready.avg` - summary of Ready conditions of all Nodes in a Cluster
=> NH-22038: Metrics for Cluster HS

deploy/k8s/manifest.yaml
this metric contains reason of Pod in case of Failed/Unknown/Pending states
=> NH-21205: Adding `k8s.pod.status.reason` metric

build/swi-k8s-opentelemetry-collector.yaml, deploy/k8s/manifest.yaml
Those attributes are not identifying the target resource, but the source where kube-state-metric is deployed on
=> NH-21202: Removing attributes that are confusing our ingestion

deploy/k8s/manifest.yaml
With previous configuration collector did not have enough memory to scrape larger environment (for example our dev-ssp)
* memory_ballast:
* according to https://github.com/open-telemetry/opentelemetry-collector/blob/main/processor/memorylimiterprocessor/README.md: `The ballast should be configured to be 1/3 to 1/2 of the memory allocated to the collector`
* so setting to 35%
* memory_limiter: using percentages instead of hard limits (which is recommended for docker environment)
=> NH-20832: Adjusting memory limits to safe values

deploy/k8s/manifest.yaml
The `memory_limiter` should be the first processor to run in the pipeline (https://github.com/open-telemetry/opentelemetry-collector/blob/main/processor/memorylimiterprocessor/README.md#memory-limiter-processor) - moving it to the top of the list. Also added the limiter for log collectors.
=> Run memory_limiter as the first processor

.circleci/config.yml, build/docker/Dockerfile, skaffold.yaml
OTEL builder produces combined `go.mod` file with dependencies of all the components, so we just need to call `go mod vendor` and send the output to mend
example scan with this setup is here: https://app.whitesourcesoftware.com/Wss/WSS.html#!project;id=4601181
=> NH-21761: adding Mend scan

deploy/k8s/manifest.yaml
Creating metrics for Pod Filesystem widgets:
- _k8s.pod.fs.reads.rate_ and _k8s.pod.fs.writes.rate_ from **container_fs_reads_total** and **container_fs_writes_total**
- _k8s.pod.fs.reads.bytes.rate_ and _k8s.pod.fs.writes.bytes.rate_ from **container_fs_reads_bytes_total**  and **container_fs_writes_bytes_total**
- _k8s.pod.fs.usage_ from **container_fs_usage_bytes**
=> NH-23685 Pod Detail Page - File system widgets

deploy/k8s/manifest.yaml
Modified `k8s.node.*` metrics calculations.
Added `k8s.node.fs.iops` and `k8s.node.fs.throughput` metrics
=> Kubernetes node metrics calculation

.github/workflows/buildAndDeploy.yml
in new version of Helm chart there is probably no component called `node-exporter` so no events are triggered
=> Fixing build

deploy/k8s/manifest.yaml
- Unify node attribute
- Fix iops and throughput metric as they were not functional due to fact that add operation needs both metrics available. 
- Add iops and throughput metric for pods
=> NH-27162 - use `instance` when `node` attribute is not present

deploy/helm/templates/common-env-config-map.yaml, deploy/helm/values.yaml, deploy/k8s/manifest.yaml
The net/http package in Go supports the use of the HTTPS_PROXY environment variable to specify the URL of the proxy server. e.g. https://proxy.mydomain.com:8080. This exposes an otel.https_proxy_url value that users can use to set the environment variable.
=> Add support for HTTPS proxies

.github/workflows/buildAndDeploy.yml, deploy/helm/Chart.yaml, deploy/k8s/manifest.yaml, doc/development.md
Renaming the `swi-k8s-opentelemetry-collector` Helm chart to `swo-k8s-collector`. The latter is the new official name. Renaming it is OK, because we haven't released it to customers, yet.
The name of the OTEL Collector binary is left unchanged (the same as the name of this repo).
=> NH-30952: Rename Helm chart 'swi-k8s-opentelemetry-collector' to 'swo-k8s-collector'

.github/workflows/buildAndDeploy.yml, skaffold.yaml
logs were not always produced, so now making sure that we test logs produced by custom `dummy` resource
=> Making build faster and more stable

.github/workflows/buildAndTest.yml
For some reason chart-releaser PR's don't trigger the build, so fixing by push events that hopefully triggers.
=> NH-29204: Fixing chart-release PR's

deploy/helm/CHANGELOG.md, deploy/helm/templates/events-collector-deployment.yaml, deploy/helm/templates/logs-daemon-set.yaml, deploy/helm/templates/metrics-deployment.yaml, deploy/k8s/manifest.yaml
This was forgotten. It makes it easier to navigate to "/metrics" internal metrics of OTEL collectors
=> Adding telemetry port to kubernetes "ports" 

deploy/helm/CHANGELOG.md, deploy/helm/Chart.yaml, deploy/helm/logs-collector-config.yaml, deploy/helm/templates/logs-daemon-set.yaml, deploy/helm/values.yaml, deploy/k8s/manifest.yaml
Explanation of the changes:
* Setting `filelog.storage`: This persist checkpoints in persistent storage, not in memory
* Setting `max_concurrent_files` to 10 (from default 1024), this is main memory optimization, reducing amount of concurrent log scans
* Increasing memory limit to `700Mi` (which should be enough for large logs)
* Having 150Mi difference between OTEL memory limit and Kubernetes memory limit, so that OTEL has enough buffer (this prevents OOMing)
Furthermore there was a bug when parsing time fraction, see https://stackoverflow.com/questions/53837975/time-parse-in-go-with-varying-fractional-second-length
=> NH-31513: Applying memory optimizations for Log collection

deploy/helm/logs-collector-config.yaml, deploy/k8s/manifest.yaml
For new pods (which were never read before so do not have checkpoint) we wouldn't catch the beginning of the logs
=> NH-31513: Fixing `start_at` to be able to read new files from the beginning

.github/workflows/buildAndDeploy.yml, skaffold.yaml
This should prevent us merging code that rely on image that does not exists in DockerHub, but the standard build passed because standard pipeline builds it.
=> NH-31513: Adding test that makes sure that Helm works without building the image

deploy/helm/CHANGELOG.md
I forgot to mention that we upgrade OTEL to 0.69.0, which is important to have in Helm chart change log
=> NH-31513: Added to changelog forgotten changes

skaffold.yaml
A follow-up to https://github.com/solarwinds/swi-k8s-opentelemetry-collector/pull/140
This fixes the `skaffold dev` loop
=> Run structure tests only in CI

deploy/helm/CHANGELOG.md, deploy/helm/templates/events-collector-deployment.yaml, deploy/helm/templates/logs-daemon-set.yaml, deploy/helm/templates/metrics-deployment.yaml
This is useful for us (for internal telemetry monitoring) as well as for the customers 
suggested by @jaroslav-fedor-swi
=> Adding prometheus annotations, so that prometheus scrape OTEL internal telemetry

deploy/helm/CHANGELOG.md, deploy/helm/logs-collector-config.yaml
Remove deployment name from logs as parsing by regex is not functional in 100% cases and can be false positive.
=> NH-30743 - remove deployment logs

deploy/helm/CHANGELOG.md, deploy/helm/templates/logs-daemon-set.yaml
This avoid unpredictable errors in scenario when previous monitoring was not deleted
=> NH-33357: Log collector suffix clusterId into folder which it mounts for checkpoints (e.q.`/var/lib/swo/checkpoints/<clusterId>`)

deploy/helm/metrics-collector-config.yaml, doc/exported_metrics.md
Extract **git_version** from **kubernetes_build_info** where **job** is either **apiserver** or **kubernetes-apiservers** (needed for compatibility with docker-desktop). Approach is to remove all datapoints related to nodes in kubernetes_build_info metric and then use **git_version** attribute of remaining datapoints to populate **sw.k8s.cluster.version**
=> NH-31472 Introduce cluster version

doc/exported_metrics.md
Columns "Unit" and "Description" were mixed together.
=> Fix Container metrics table in documentation

tests/deploy/base/mocks.yaml
OTEL Collector in version 0.70.0 implemented buffered writes for `fileexporter`, which breaks our tests. Implement a workaround, since it cannot be disabled at this time.
=> Disable buffered writes for fileexporter used as mock in tests

doc/development.md, tests/integration/test_metric_collection.py, tests/integration/test_utils.py, utils/set_expected_output.py
No need to run tests with adjusted launch.json anymore. Just run `utils/set_expected_output.py`
=> Simplifying modification of `expected_output.json`

.github/workflows/buildAndDeploy.yml, .github/workflows/releaseHelm.yaml, .gitignore, README.md, deploy/helm/CHANGELOG.md, deploy/helm/Chart.lock, deploy/helm/Chart.yaml, deploy/helm/templates/metrics-collector-env-config-map.yaml, deploy/helm/templates/metrics-deployment.yaml, deploy/helm/values.yaml, doc/development.md, skaffold.yaml
Add option to deploy a Prometheus as part of the k8s collector chart installation.
This is controlled by a new setting `prometheus.enabled: true`.
This PR adds the [prometheus](https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus) as a dependency.
=> NH-34558: Add Prometheus as a sub-chart

deploy/helm/CHANGELOG.md, deploy/helm/Chart.yaml, deploy/helm/metrics-collector-config.yaml, skaffold.yaml, tests/deploy/tests/test_metric_manifest.yaml, tests/integration/expected_output.json, tests/integration/test_utils.py
Dependent on https://github.com/solarwinds/swi-k8s-opentelemetry-collector/pull/243 as the image will be released after its merging.
* UID attributes are removed from expected outcome of integration test, as they are extracted from real resource and they will be different in each environment
* releasing `2.3.0-alpha.6` as part of this
=> NH-34014: Updating Helm chart, using latest image and scraping labels/annotations from all supported kubernetes services

deploy/helm/CHANGELOG.md, deploy/helm/metrics-collector-config.yaml, tests/integration/expected_output.json
no longer use `container_spec_memory_limit_bytes` provided by container runtime, but `kube_pod_container_resource_limits` which use KubeAPI
=> NH-36860: Fixing calculation of `k8s.pod.spec.memory.limit`

build/swi-k8s-opentelemetry-collector.yaml
Fixing: 
* [CVE-2023-28840⁠](https://dso.docker.com/cve/CVE-2023-28840)
* [CVE-2020-8911⁠](https://dso.docker.com/cve/CVE-2020-8911)
* [CVE-2020-8912⁠](https://dso.docker.com/cve/CVE-2020-8912)
* [CVE-2019-3826⁠](https://dso.docker.com/cve/CVE-2019-3826)
Those are fixed in OTEL 0.76.0, but that version is not yet released so patching this manually
=> NH-39357 [Security][swi-k8s-opentelemetry-collector][Docker Scout] CVE-2023-28840 moby

build/docker/Dockerfile
Fixing CVE-2023-24537. Ref ticket that fixes this in Go in 1.19.8: https://github.com/golang/go/issues/59273
=> NH-39355 [Security][swi-k8s-opentelemetry-collector][Docker Scout] CVE-2023-24537 stdlib 1.19.7

.github/dependabot.yaml
Adopts GitHub Dependabot for updating dependencies and staying on top of routine & security updates.
=> Experiment: setting up dependabot

.github/workflows/buildAndDeploy.yml, src/processor/swmetricstransformprocessor/metrics_testcase_builder_test.go, src/processor/swmetricstransformprocessor/operation_filter_datapoints.go, src/processor/swmetricstransformprocessor/processor_testcases_test.go
https://swicloud.atlassian.net/browse/NH-35637
sometimes the datapoint does not have any value, but just flag. Something like this:
```
"dataPoints": [
{ "timeUnixNano": "1683187000677000000", "flags": 1 }
]
```
where flag=1 just indicates that there is no value. Our filterDatapoints didn't count with datapoints without value.
=> NH-35637: k8s.kube_pod_status_phase is send with value 0

build/swi-k8s-opentelemetry-collector.yaml
increasing protobuf version because of security issue (we can also increase otel collector version, but there are breaking changes, so there is separate task for it)
=> NH-40779 patching dependencies

build/docker/structure-test.yaml, build/swi-k8s-opentelemetry-collector.yaml
this is needed to connect two pipelines. This is required for https://github.com/solarwinds/swi-k8s-opentelemetry-collector/pull/292
=> NH-41723: Updating image with forwardconnector

build/docker/structure-test.yaml, build/swi-k8s-opentelemetry-collector.yaml, src/processor/k8sattributesprocessor/config.go, src/processor/k8sattributesprocessor/config_test.go, src/processor/k8sattributesprocessor/factory.go, src/processor/k8sattributesprocessor/factory_resource.go, src/processor/k8sattributesprocessor/internal/kube/client.go, src/processor/k8sattributesprocessor/internal/kube/client_resource.go, src/processor/k8sattributesprocessor/internal/kube/client_resource_test.go, src/processor/k8sattributesprocessor/internal/kube/client_test.go, src/processor/k8sattributesprocessor/internal/kube/informer_resource.go, src/processor/k8sattributesprocessor/internal/kube/informer_resource_test.go, src/processor/k8sattributesprocessor/internal/kube/kube_resource.go, src/processor/k8sattributesprocessor/internal/observability/observability.go, src/processor/k8sattributesprocessor/internal/observability/observability_resource.go, src/processor/k8sattributesprocessor/options.go, src/processor/k8sattributesprocessor/options_resource.go, src/processor/k8sattributesprocessor/processor.go, src/processor/k8sattributesprocessor/testdata/config.yaml
* this will be published to Docker hub as 0.7.0 version
* adding `persistentvolume` and `persistentvolumeclaim` sections to k8sattributes processor and adding labels/annotations extractions
* there were forgotten observability metrics so I added them for some other resources
=> NH-40558: Adding PV and PVC labels/annotations instrumentation

deploy/helm/CHANGELOG.md, deploy/helm/Chart.yaml, deploy/helm/templates/autoupdate/autoupdate-cronjob.yaml, deploy/helm/templates/metrics-deployment.yaml, deploy/helm/templates/swo-agent-statefulset.yaml, deploy/helm/values.yaml, tests/integration/expected_output.json
Updating docker images `solarwinds/swo-agent`, `busybox`, `fullstorydev/grpcurl` and `alpine/k8s` to latest available versions.
=> NH-42434: Use specific versions of 3rd party docker images

build/docker/structure-test.yaml, build/swi-k8s-opentelemetry-collector.yaml
increasing version of github.com/docker/distribution because of security issue
current image
new image
=> NH-43083 increasing version of build dependency

deploy/helm/CHANGELOG.md, deploy/helm/templates/logs-fargate-config-map.yaml, deploy/helm/templates/logs-fargate-namespace.yaml, deploy/helm/tests/__snapshot__/logs-fargate-config-map_test.yaml.snap, deploy/helm/tests/logs-fargate-config-map_test.yaml, deploy/helm/values.yaml, doc/development.md
Create a special NameSpace and ConfigMap configured to send logs to `aws/eks/{{ $name }}/application` CloudWatch log group, where `{{ $name }}` is a sanitized cluster name.
The ConfigMap is configured to enrich logs with `sw.k8s.cluster.uid`and `sw.k8s.log.type` attributes.
=> NH-53106: Add EKS Fargate logging support

deploy/helm/CHANGELOG.md, deploy/helm/Chart.yaml, deploy/helm/values.yaml, tests/integration/expected_output.json
- There are new Helm settings `aws_fargate.enabled` and `aws_fargate.logs.enabled` that allow the k8s collector Helm chart to setup AWS EKS Fargate logging ConfigMap
- Log collection DaemonSet now restrict where it runs:
- Fargate nodes are excluded
- Only linux nodes with amd64 architecture are included
- Fixed Journal log collection on EKS (and other environment where journal logs are stored in `/var/log/journal`)
=> NH-53106: Release chart 2.7.0-alpha.3

deploy/helm/CHANGELOG.md, deploy/helm/Chart.yaml, deploy/helm/templates/metrics-collector-env-config-map.yaml, deploy/helm/tests/__snapshot__/logs-fargate-config-map_test.yaml.snap, deploy/helm/values.yaml, tests/integration/expected_output.json
Also allowed use of `prometheus.forceNamespace` option of bundled prometheus, to force namespace where prometheus is deployed (allow other namespace than the one where Helm chart is installed). This is useful when Fargate is restricted to specific namespace
=> NH-53106: Adjusted bundled prometheus to not run on Fargate nodes by default

deploy/helm/CHANGELOG.md, deploy/helm/Chart.yaml, deploy/helm/metrics-collector-config.yaml, deploy/helm/templates/_helpers.tpl, deploy/helm/tests/__snapshot__/events-collector-config-map_test.yaml.snap, deploy/helm/tests/__snapshot__/logs-fargate-config-map_test.yaml.snap, deploy/helm/tests/__snapshot__/metrics-collector-config-map_test.yaml.snap, tests/integration/expected_output.json, tests/integration/test_utils.py
`k8s.node.name` attributes from metrics often includes host name and not actual node name (they differ in case of Fargate). So I am setting the same mechanism we already previously did for Events. To remove `k8s.node.name` attribute if it does not match actual node name. 
In the same time I added instrumentation of `k8s.node.name` which should cover cases when it does not exists.
=> NH-53106: Handling `k8s.node.name` attributes from Metrics correctly

build/docker/Dockerfile, build/docker/structure-test.yaml, build/swi-k8s-opentelemetry-collector.yaml
Updating:
* go build image to `1.21.0`
* `jaegertracing/jaeger` to `v1.47`
* `golang.org/x/net` to `v0.13.0`
* `aws-sdk-go` to `v1.44.333`
Marking the new image as `0.8.2`
=> NH-47025: Update dependencies

deploy/helm/CHANGELOG.md, deploy/helm/Chart.yaml, deploy/helm/metrics-collector-config.yaml, deploy/helm/tests/__snapshot__/logs-fargate-config-map_test.yaml.snap, deploy/helm/tests/__snapshot__/metrics-collector-config-map-fargate_test.yaml.snap, deploy/helm/tests/metrics-collector-config-map-fargate_test.yaml, tests/integration/expected_output.json
* renamed `instance` to `service.instance.id` as for some time `instance` no longer goes from prometheusreciever (see BREAKING CHANGES of https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/CHANGELOG.md#v0470) 
* `kubernetes_io_hostname` must be ignored on Fargate nodes so adding condition there
* `service.instance.id` fallback should cover non-fargate nodes in Fargate cluster. On EKS it should always contain real node
* presence of `kubernetes_io_hostname` in non-fargate cluster should cover most of the use cases where `service.instance.id` is malformed (e.q. docker-desktop when there is ip address instead of real node name)
=> NH-53106: Fixing usage metrics

.dockerignore, .github/workflows/buildAndDeploy.yml, build/docker/Dockerfile.Windows
* Added separate publishing Job for windows image
* Windows is going to be build only in event of release. The image is not needed for any other part of the workflow and we can quite rely on the Go that if the build of OTEL fails on Windows it would have failed on Linux as well
=> NH-54277: Adding Windows image tag

tests/integration/test_metric_collection.py
pvc annotations are delayes and in case first prometheus scrape doesn't have them then whole test will fail
=> Stability integration tests 

deploy/helm/CHANGELOG.md, deploy/helm/logs-collector-config.yaml, deploy/helm/tests/__snapshot__/logs-collector-config-map-windows_test.yaml.snap, deploy/helm/tests/__snapshot__/logs-collector-config-map_test.yaml.snap
Syslog attributes should not be necessary anymore according to  https://swicloud.atlassian.net/wiki/spaces/SP/pages/3706519849/TIP-8+Minimal+Otel+Log+Support
=> NH-62317 removing syslog attributes

build/docker/Dockerfile
each COPY in end image has separate layer, so adding extra stage and merging all COPY commands into single layer
=> Optimizing docker layers, having all binaries for journalctl in one

deploy/helm/CHANGELOG.md, deploy/helm/metrics-collector-config.yaml, deploy/helm/tests/__snapshot__/metrics-collector-config-map-fargate_test.yaml.snap, deploy/helm/tests/__snapshot__/metrics-collector-config-map_test.yaml.snap, tests/integration/expected_output.json, tests/integration/test_metric_collection.py
Removed attributes `net.host.name`, `net.host.port`, `http.scheme`, `prometheus`, `prometheus_replica` and `endpoint` from exported metrics.
Some of them were filtered out even before, but they were renamed later, so the filters stopped working.
=> NH-60899: Unexport attributes

build/docker/Dockerfile.Windows
On GitHub actions I got: 
```
wrapper: go build wrapper: copying C:\Windows\TEMP\go-build792349289\b001\exe\a.out.exe: open /wrapper.exe: Access is denied.
The command 'cmd /S /C go build -a -o /wrapper.exe' returned a non-zero code: 1
```
see: https://github.com/solarwinds/swi-k8s-opentelemetry-collector/actions/runs/6458171456/job/17531295588
This was not reproducible locally on Windows 10. This fixes it.
=> NH-57813: Fixing windows docker image

.github/actions/deploy-kubernetes/action.yml, .github/actions/deploy-skaffold/action.yml, .github/actions/run-integration-tests/action.yaml, .gitignore, doc/development.md, skaffold.yaml, tests/deploy/base/mocks.yaml, tests/deploy/tests/integrationTestCronJob.yaml, tests/deploy/tests/test_metric_manifest.yaml, tests/deploy/wiremock/kustomization.yaml, tests/deploy/wiremock/wiremock.yaml, tests/integration/expected_output.json, tests/integration/test_events_collection.py, tests/integration/test_log_collection.py
I developed this as part of eBPF efforts, since eBPF cannot be tested on local docker-desktop
Generally:
* adjusting manifests so that namespace can be overridden, in order to make that happen I had to updated resources to be deployed to single namespace and leverage `defaultNamespace` option for mocks
* creating new skaffold profile
* moving wiremock to separate manifest so that it can be excluded from deployment
* updating timeseries-mock-service and removing console log as it slows it down and is unnecessary
* documentation
=> NH-63239: Making it possible to dev against remote test-cluster

deploy/helm/CHANGELOG.md, deploy/helm/Chart.yaml, deploy/helm/templates/metrics-deployment.yaml, deploy/helm/tests/__snapshot__/logs-fargate-config-map_test.yaml.snap, tests/integration/expected_output.json
If `otel.metrics.prometheus.url` is empty, it ignores `otel.metrics.prometheus_check` to not fail on missing Prometheus
=> NH-63239: Fix of prometheus check

deploy/helm/CHANGELOG.md, deploy/helm/templates/network/kernel-collector-daemonset.yaml, deploy/helm/templates/node-collector-daemon-set.yaml, deploy/helm/tests/__snapshot__/kernel-collector-daemonset_test.yaml.snap, deploy/helm/tests/__snapshot__/node-collector-daemon-set_test.yaml.snap, deploy/helm/tests/kernel-collector-daemonset_test.yaml, deploy/helm/values.yaml, skaffold.yaml
When `hostNetwork: true` is set (which is case when ebpf is enabled) it automatically mounts all ports to host port, which is problem in case of node-collector. 
This was solved by separating kernel-collector into separate daemonset
=> NH-63239: node-collector no longer mounts `nodePort`.

deploy/helm/CHANGELOG.md, deploy/helm/Chart.yaml, deploy/helm/metrics-collector-config.yaml, deploy/helm/tests/__snapshot__/logs-fargate-config-map_test.yaml.snap, deploy/helm/tests/__snapshot__/metrics-collector-config-map-fargate_test.yaml.snap, deploy/helm/tests/__snapshot__/metrics-collector-config-map_test.yaml.snap, skaffold.yaml, tests/integration/expected_output.json
* correctly filtering out ebpf_net metrics (those are internal metrics that customers does not need and can be opt-in via values.yaml)
* prefixing all metrics that arrives to OTEL endpoint with `k8s`, not just ebpf ones (for now it won't have impact, but in case customers would use that endpoint we would prefix it as well)
=> NH-63239: correctly filtering out `ebpf_net` metrics by default

deploy/helm/CHANGELOG.md, deploy/helm/Chart.yaml, deploy/helm/node-collector-config.yaml, deploy/helm/templates/node-collector-daemon-set-windows.yaml, deploy/helm/templates/node-collector-daemon-set.yaml, deploy/helm/tests/__snapshot__/events-collector-deployment_test.yaml.snap, deploy/helm/tests/__snapshot__/metrics-deployment_test.yaml.snap, deploy/helm/tests/__snapshot__/node-collector-config-map-windows_test.yaml.snap, deploy/helm/tests/__snapshot__/node-collector-config-map_test.yaml.snap, deploy/helm/tests/__snapshot__/node-collector-daemon-set-windows_test.yaml.snap, deploy/helm/tests/__snapshot__/node-collector-daemon-set_test.yaml.snap, deploy/helm/values.yaml, tests/deploy/tests/test_metric_manifest.yaml, tests/integration/expected_telemetry/deployment.json, tests/integration/expected_telemetry/deployment_with_metric.json, tests/integration/expected_telemetry/pod.json, tests/integration/test_metric_collection.py
Depends on: https://github.com/solarwinds/swi-k8s-opentelemetry-collector/pull/447
Summary:
* Added metrics pipeline to node-collector
* Adding support for scraping application metrics with configurable custom rule
* `k8sattributes` configured to watch only entities from `NODE_NAME` (to reduce memory footprint)
* `k8s_observer` configured to watch only pods from `NODE_NAME`
* `receiver_creator` creates `promethesreceiver` for each discovered Pod on given node
=> NH-66305: Adding support for scraping application metrics

deploy/helm/CHANGELOG.md, deploy/helm/metrics-collector-config.yaml, deploy/helm/templates/NOTES.txt, deploy/helm/tests/metrics-collector-config-map_test.yaml, deploy/helm/tests/notes_test.yaml, deploy/helm/values.yaml
Depends on https://github.com/solarwinds/swi-k8s-opentelemetry-collector/pull/448 
To avoid scraping metrics from both Prometheus and using autodiscovery of application metrics I ignore `extra_scrape_metrics` if `otel.metrics.autodiscovery.prometheusEndpoints.enabled` is enabled (true by default). Customer can override this behavior with `force_extra_scrape_metrics` if he is really sure extra scraped metrics are not autodiscovered
=> NH-66305: Adding `force_extra_scrape_metrics` option

deploy/helm/CHANGELOG.md, deploy/helm/events-collector-config.yaml, deploy/helm/metrics-collector-config.yaml, deploy/helm/node-collector-config.yaml, deploy/helm/tests/__snapshot__/events-collector-config-map_test.yaml.snap, deploy/helm/tests/__snapshot__/metrics-collector-config-map-fargate_test.yaml.snap, deploy/helm/tests/__snapshot__/metrics-collector-config-map_test.yaml.snap, deploy/helm/tests/__snapshot__/node-collector-config-map-windows_test.yaml.snap, deploy/helm/tests/__snapshot__/node-collector-config-map_test.yaml.snap, deploy/helm/values.yaml
Depends on https://github.com/solarwinds/swi-k8s-opentelemetry-collector/pull/464 (to avoid merge conflicts)
This follows on this thread: https://swicloud.slack.com/archives/C02HF9XCHB8/p1698707326607679
we are getting a lot of `DeadlineExceeded` errors here and there and even if we have backoff retry which will make sure that it will try again, it is increasing memory usage and also some data may be written twice, as writes on the backend are not transactional and they can be successfully written to kafka even if request fails.
Therefore setting default of `initial_interval` to `10s` (previously was `5s`)
=> Added option to configure retry_on_failure and increasing GRPC request timeout

deploy/helm/CHANGELOG.md, deploy/helm/templates/events-collector-deployment.yaml, deploy/helm/templates/metrics-deployment.yaml, deploy/helm/templates/node-collector-daemon-set-windows.yaml, deploy/helm/templates/node-collector-daemon-set.yaml, deploy/helm/tests/__snapshot__/events-collector-deployment_test.yaml.snap, deploy/helm/tests/__snapshot__/metrics-deployment_test.yaml.snap, deploy/helm/tests/__snapshot__/node-collector-daemon-set-windows_test.yaml.snap, deploy/helm/tests/__snapshot__/node-collector-daemon-set_test.yaml.snap, deploy/helm/values.yaml
Added option to configure terminationGracePeriodSeconds defaulting to 10 minutes, so that it is guaranteed that collector process whole pipeline
=> NH-67743: Improving graceful termination

deploy/helm/CHANGELOG.md, deploy/helm/Chart.yaml, deploy/helm/templates/metrics-deployment.yaml, deploy/helm/tests/__snapshot__/logs-fargate-config-map_test.yaml.snap, deploy/helm/tests/__snapshot__/metrics-deployment_test.yaml.snap, deploy/helm/values.yaml
The reason is that metrics collector newly has OTLP endpoint and healthcheck does not test its availability, so adding initial delay just to make sure that pod gets ready after the endpoint is available
=> NH-67033: Added option to configure liveness and readiness probes initial startup delay on metrics collector

.github/workflows/buildAndDeploy.yml, build/docker/Dockerfile, build/docker/copy-journalbinary.sh, build/docker/structure-test.yaml, build/swi-k8s-opentelemetry-collector.yaml
* making dockerfile platform agnostic
* it is no longer possible to use sha256 with base images
* building amd64 and arm64 platforms (it is no longer possible to save/load tar, it must be built in step together with push)
* ARM64 is built using QEMU emulation and due to that its building is very slow (takes like 25 minutes), but it is not the issue since we build our image quite rarely.
=> NH-42143: Building multiarch image with AMD64 and ARM64 platforms

build/docker/Dockerfile, build/docker/structure-test.yaml, build/swi-k8s-opentelemetry-collector.yaml
In previous PR I set base image to `bash` (which I needed for debugging) and forgot to turn it back. So it is accidental.
=> NH-42143: Reverting base image to `scratch`

deploy/helm/CHANGELOG.md, deploy/helm/Chart.yaml, deploy/helm/templates/_helpers.tpl, deploy/helm/templates/autoupdate/autoupdate-cronjob.yaml, deploy/helm/templates/events-collector-deployment.yaml, deploy/helm/templates/metrics-deployment.yaml, deploy/helm/templates/network/k8s-collector-deployment.yaml, deploy/helm/templates/network/kernel-collector-daemonset.yaml, deploy/helm/templates/network/reducer-deployment.yaml, deploy/helm/templates/node-collector-daemon-set-windows.yaml, deploy/helm/templates/node-collector-daemon-set.yaml, deploy/helm/templates/secret.yaml, deploy/helm/templates/swo-agent-statefulset.yaml, deploy/helm/tests/__snapshot__/events-collector-deployment_test.yaml.snap, deploy/helm/tests/__snapshot__/k8s-collector-deployment_test.yaml.snap, deploy/helm/tests/__snapshot__/kernel-collector-daemonset_test.yaml.snap, deploy/helm/tests/__snapshot__/logs-fargate-config-map_test.yaml.snap, deploy/helm/tests/__snapshot__/metrics-deployment_test.yaml.snap, deploy/helm/tests/__snapshot__/node-collector-daemon-set-windows_test.yaml.snap, deploy/helm/tests/__snapshot__/node-collector-daemon-set_test.yaml.snap, deploy/helm/tests/__snapshot__/reducer-deployment_test.yaml.snap, deploy/helm/tests/events-collector-deployment_test.yaml, deploy/helm/tests/metrics-deployment_test.yaml, deploy/helm/tests/node-collector-daemon-set-windows_test.yaml, deploy/helm/tests/node-collector-daemon-set_test.yaml, deploy/helm/tests/swo-agent-statefulset_test.yaml, deploy/helm/values.yaml
* Adding `common.image` which can override image from existing locations as well as from azure
* Covering all use cases via helm unit tests
* setting chart appVersion in unit tests so that we don't need to regenerate them with every bump
* Added `otel.api_token` to allow setting API token for OTEL collector through `values.yaml`
* Instrumented all pods with `azure-extensions-usage-release-identifier` on AKS
=> NH-66009: Adjust helm chart to meet AKS requirements

.github/actions/deploy-kubernetes/action.yml, .github/workflows/buildAndDeploy.yml, deploy/helm/templates/_helpers.tpl, deploy/helm/templates/cluster-role-binding.yaml, deploy/helm/templates/cluster-role.yaml, deploy/helm/templates/collector-service.yaml, deploy/helm/templates/common-env-config-map.yaml, deploy/helm/templates/events-collector-config-map.yaml, deploy/helm/templates/events-collector-deployment.yaml, deploy/helm/templates/logs-fargate-config-map.yaml, deploy/helm/templates/logs-fargate-namespace.yaml, deploy/helm/templates/metrics-collector-config-map.yaml, deploy/helm/templates/metrics-collector-env-config-map.yaml, deploy/helm/templates/metrics-deployment.yaml, deploy/helm/templates/network/configmap.yaml, deploy/helm/templates/network/k8s-collector-clusterrole.yaml, deploy/helm/templates/network/k8s-collector-clusterrolebinding.yaml, deploy/helm/templates/network/k8s-collector-deployment.yaml, deploy/helm/templates/network/kernel-collector-daemonset.yaml, deploy/helm/templates/network/reducer-deployment.yaml, deploy/helm/templates/network/reducer-service.yaml, deploy/helm/templates/node-collector-config-map-windows.yaml, deploy/helm/templates/node-collector-config-map.yaml, deploy/helm/templates/node-collector-daemon-set-windows.yaml, deploy/helm/templates/node-collector-daemon-set.yaml, deploy/helm/templates/secret.yaml, deploy/helm/templates/service-account.yaml, deploy/helm/templates/swo-agent-statefulset.yaml
* Previously user got some random rendering error if he had unsupported Helm version. Now we are failing fast with human message
* Version 3.10.3 is known that has all features we use, it is already 1 year old so it shouldn't limit users
=> Adding minimal Helm version constraint

.github/dependabot.yaml
According to https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#docker
> Dependabot can update Docker image tags in Kubernetes manifests. Add an entry to the Docker package-ecosystem element of your dependabot.yml file for each directory containing a Kubernetes manifest which references Docker image tags. Kubernetes manifests can be Kubernetes Deployment YAML files or Helm charts
so trying that out
=> Configuring dependabot to update docker images in Helm chart templates

deploy/helm/CHANGELOG.md, deploy/helm/Chart.yaml, deploy/helm/templates/node-collector-daemon-set-windows.yaml, deploy/helm/tests/__snapshot__/logs-fargate-config-map_test.yaml.snap, deploy/helm/tests/__snapshot__/node-collector-daemon-set-windows_test.yaml.snap, deploy/helm/tests/node-collector-daemon-set-windows_test.yaml
* Using 0.8.13 which has both Windows OS supported in it
* using `-nanoserver` tag (see https://hub.docker.com/layers/solarwinds/swi-opentelemetry-collector/0.8.13-nanoserver/images/sha256-54b9a100b02d930ab64dd79058cb710ecb07365aff335680e849e61c68e00705?context=repo)
the image obviously has multiple OS versions in it, hopefully windows node will pick the one it needs
`docker manifest inspect solarwinds/swi-opentelemetry-collector:0.8.13-nanoserver`:
```
{
"schemaVersion": 2,
"mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
"manifests": [
{
"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
"size": 1369,
"digest": "sha256:54b9a100b02d930ab64dd79058cb710ecb07365aff335680e849e61c68e00705",
"platform": {
"architecture": "amd64",
"os": "windows", …
```
=> NH-63828 Support for Windows Server 2019

build/docker/Dockerfile, build/docker/structure-test.yaml, build/swi-k8s-opentelemetry-collector.yaml, deploy/helm/Chart.yaml
Since EKS Add-on require to image scans as part of validation, we need to move to supported base image.
=> Move to apline

build/docker/Dockerfile, build/docker/structure-test.yaml, build/swi-k8s-opentelemetry-collector.yaml
* ECR does support alpine:18 - https://github.com/aws/containers-roadmap/issues/2027
* ECR does NOT support alpine:19 yet - https://github.com/aws/containers-roadmap/issues/2237
=> NH-68604: Updating base image to alpine:18

build/docker/Dockerfile, build/docker/structure-test.yaml, build/swi-k8s-opentelemetry-collector.yaml
* That should not have security vulnerabilities. 
* Using last digest of multi-arch image, dependabot should update that every week
=> NH-68604: Using distroless image as base

deploy/helm/CHANGELOG.md, deploy/helm/Chart.yaml, deploy/helm/metrics-collector-config.yaml, deploy/helm/node-collector-config.yaml, deploy/helm/tests/__snapshot__/logs-fargate-config-map_test.yaml.snap, deploy/helm/tests/__snapshot__/metrics-collector-config-map-fargate_test.yaml.snap, deploy/helm/tests/__snapshot__/metrics-collector-config-map_test.yaml.snap, deploy/helm/tests/__snapshot__/node-collector-config-map-windows_test.yaml.snap, deploy/helm/tests/__snapshot__/node-collector-config-map_test.yaml.snap, doc/exported_metrics.md
All histogram metrics are filtered out.
For Istio metrics, publish `k8s.istio_request_bytes.rate`, `k8s.istio_response_bytes.rate` and `k8s.istio_request_duration_milliseconds.rate` instead.
=> NH-67458: Make sure no histogram metrics are sent to SWO

deploy/helm/CHANGELOG.md, deploy/helm/Chart.yaml, deploy/helm/node-collector-config.yaml, deploy/helm/tests/__snapshot__/logs-fargate-config-map_test.yaml.snap, deploy/helm/tests/__snapshot__/node-collector-config-map_test.yaml.snap, deploy/helm/tests/node-collector-config-map_test.yaml
When both Prometheus autodiscovery and Fargate support were disabled, the `k8s_observer` extension would not be configured, even though the pipeline would still depend on it.
=> Fix disabled autodiscovery

.github/cr.sh, .github/workflows/releaseHelm.yaml
* removed `--pr` flag from `cr index` which means that `index.yaml` is produced locally
* pushing commit manually using gh cli as GitHub actions bot which is automatically signed
* creating PR manually using gh cli
=> NH-69902: Fixing code signing for Helm releaser

deploy/helm/CHANGELOG.md, deploy/helm/Chart.yaml, deploy/helm/events-collector-config.yaml, deploy/helm/metrics-collector-config.yaml, deploy/helm/node-collector-config.yaml, deploy/helm/tests/__snapshot__/logs-fargate-config-map_test.yaml.snap, deploy/helm/tests/__snapshot__/node-collector-config-map-windows_test.yaml.snap, deploy/helm/tests/__snapshot__/node-collector-config-map_test.yaml.snap, deploy/helm/values.yaml
- Added option to configure `timeout`, which is time to wait per individual attempt to send data to SWO.
- default is `15s` (previously was `5s`) avoiding unnecessary retries when backend takes time to respond
=> Added option to configure `timeout` for 3.3.0

deploy/helm/CHANGELOG.md, deploy/helm/node-collector-config.yaml, deploy/helm/tests/__snapshot__/node-collector-config-map_test.yaml.snap
Using a single file glob (`--file`) for both `/var/log/journal/` and `/run/log/journal/`.
If they are specified separately, or using a directory (`--directory`) instead of a file blob, the journalctl will return error when one of the paths does not contain journal logs. And the OTEL `journaldreceiver` will stop working when that happens.
Using merge (`--merge`) would work, too, but that is not supported by the `journaldreceiver`.
=> Fix collecting Journal logs from `/var/log/journal`

deploy/helm/CHANGELOG.md, deploy/helm/Chart.yaml, deploy/helm/templates/logs-fargate-config-map.yaml, deploy/helm/tests/__snapshot__/logs-fargate-config-map_test.yaml.snap
Disable support for https://docs.fluentbit.io/manual/pipeline/filters/kubernetes#kubernetes-pod-annotations.
Container logs from AWS EKS Fargate clusters are now sent to SWO as-is. `fluentbit.io/parser` and `fluentbit.io/exclude` annotations are ignored. This both fixes an issue with "empty" JSON logs sent to SWO and aligns the behavior with non-Fargate container logs.
=> Disable FluentBit log parsing on EKS Fargate

.github/workflows/buildAndDeploy.yml, deploy/helm/CHANGELOG.md, deploy/helm/Chart.yaml, deploy/helm/templates/autoupdate/autoupdate-cronjob.yaml, deploy/helm/templates/metrics-deployment.yaml, deploy/helm/templates/network/k8s-collector-deployment.yaml, deploy/helm/templates/network/kernel-collector-daemonset.yaml, deploy/helm/templates/network/reducer-deployment.yaml, deploy/helm/templates/swo-agent-statefulset.yaml, deploy/helm/tests/__snapshot__/logs-fargate-config-map_test.yaml.snap, deploy/helm/values.schema.json, deploy/helm/values.yaml, doc/development.md
The Helm chart now contains `values.schema.json`, which is used to validate user-provided configuration during installation/upgrade.
Summary of changes:
* Added schema to `deploy/helm/values.schema.json`.
* Subchart sections are included, but only to the extend that we want customers to configure. E.g. container images used in them.
* Schemas for k8s objects are included directly in the schema. Unfortunately, there is no official JSON schema that could be referenced, instead.
* The schema checks for typos and unexpected settings/sections. :warning: This means that if there are invalid settings in the `values.yaml` provided by customers, the validation will fail with an error.
For example, if there is a setting `something_unexpected: "whatever"` in the file, this will be the error:
``` …
```
=> Add JSON schema validation for the Helm chart

src/cmd/go.mod, src/cmd/go.sum, tests/integration/test_log_collection.py
Update of OTEL collector to 0.98.0 in PR #579 introduced a change in how logs were recombined. Update the `stanza` package to the version, in which it allows to restore previous behavior. There is no other change in the package since 0.98.0.
=> Update stanza package to restore a behavior from before update to 0.98.0

.github/workflows/buildAndDeploy.yml
It's a workaround for AWS security scanner, which cannot handle images with such data
=> Disable Docker image attestations

.github/dependabot.yaml
This is what is written in [doc](https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates#overriding-the-default-behavior-with-a-configuration-file):
> If you only require security updates and want to exclude version updates, you can set open-pull-requests-limit to 0 in order to prevent version updates for a given package-ecosystem.
Changes in this PR:
* Removing updates of go.mod in custom processors (as it cannot be done without update of main go.mod anyway)
* Disabling version updates of main go.mod
* Scheduled to run daily
=> Reconfiguring dependabot to do only security updates in go.mod

README.md, deploy/helm/CHANGELOG.md, deploy/helm/Chart.yaml, deploy/helm/events-collector-config.yaml, deploy/helm/metrics-collector-config.yaml, deploy/helm/node-collector-config.yaml, deploy/helm/tests/__snapshot__/logs-fargate-config-map_test.yaml.snap, deploy/helm/tests/__snapshot__/metrics-collector-config-map-fargate_test.yaml.snap, deploy/helm/tests/__snapshot__/metrics-collector-config-map_test.yaml.snap, deploy/helm/tests/__snapshot__/node-collector-config-map-windows_test.yaml.snap, deploy/helm/tests/__snapshot__/node-collector-config-map_test.yaml.snap, deploy/helm/values.yaml, skaffold.yaml
Change the `otel.metrics.filter`, `otel.logs.filter` and `otel.events.filter` settings to be able to access resource attributes.
There are several useful resource attributes like `k8s.deployment.name`, ... that are added to metrics/logs/events during the processing pipeline. And the filter was applied before these attributes were added to the data.
⚠️ This is a breaking change for logs and events.
Event filtering is probably not used by anyone, anyway. But log filtering is - customers tend to adjust it to include all logs, not just the default subset. We could special case that common scenario in a future PR and make such configuration compatible with the changes in this PR. But I don't see how to resolve this automatically for any custom configuration.
The issue is with filters that …
=> Allow filtering by resource attributes

README.md, deploy/helm/CHANGELOG.md, deploy/helm/events-collector-config.yaml, deploy/helm/metrics-collector-config.yaml, deploy/helm/node-collector-config.yaml, deploy/helm/templates/NOTES.txt, deploy/helm/templates/_common-config.tpl, deploy/helm/templates/_helpers.tpl, deploy/helm/tests/__snapshot__/events-collector-config-map_test.yaml.snap, deploy/helm/tests/__snapshot__/metrics-collector-config-map-fargate_test.yaml.snap, deploy/helm/tests/__snapshot__/metrics-collector-config-map_test.yaml.snap, deploy/helm/tests/__snapshot__/node-collector-config-map-windows_test.yaml.snap, deploy/helm/tests/__snapshot__/node-collector-config-map_test.yaml.snap, deploy/helm/tests/events-collector-config-map_test.yaml, deploy/helm/tests/node-collector-config-map_test.yaml, deploy/helm/values.yaml, skaffold.yaml
A continuation of PR #628.
Restore backwards compatibility for `otel.metrics.filter`, `otel.logs.filter` and `otel.events.filter` (follow-up to 5b8d2c7)
The basic idea is that when users are setting the filters using old filtering syntax, we merge them with the default filters in the old syntax and use the old attributes behavior (they are in records).
And when they use the new syntax, we merge them with the default filters in the new syntax and use the new attributes behavior (they are in resources).
Because the new syntax and the old syntax are not compatible (they cannot be used both at the same time), and until now we forced users to use the old syntax (because our default filters were using the old syntax), we can use this as the "master" switch, allowing for backwards compatibility.
=> Add support for new filtering syntax

deploy/helm/CHANGELOG.md, deploy/helm/Chart.yaml, deploy/helm/node-collector-config.yaml, deploy/helm/tests/__snapshot__/logs-fargate-config-map_test.yaml.snap, deploy/helm/tests/__snapshot__/node-collector-config-map-windows_test.yaml.snap, deploy/helm/tests/__snapshot__/node-collector-config-map_test.yaml.snap
Restore the behavior from the last stable k8s collector (3.3.x) and remove filtering of journal logs. They do not contain as many attributes as normal logs, so most of the filters would cause us to drop all journal logs.
=> Fix filtering with the new syntax for journal logs

.github/cr.sh
The base64 encode became too large to be used as a command line argument
=> Fix for large Helm index

deploy/helm/CHANGELOG.md, deploy/helm/Chart.yaml, deploy/helm/metrics-collector-config.yaml, deploy/helm/tests/__snapshot__/logs-fargate-config-map_test.yaml.snap, deploy/helm/tests/__snapshot__/metrics-collector-config-map-fargate_test.yaml.snap, deploy/helm/tests/__snapshot__/metrics-collector-config-map_test.yaml.snap, deploy/helm/tests/swo-agent-statefulset_test.yaml, deploy/helm/values.yaml
- Upgraded collector image to `0.10.2`
- https://github.com/solarwinds/swi-k8s-opentelemetry-collector/compare/0.10.1...0.10.2
- Upgraded SWO Agent image to `v2.8.90`
- Additional improvements to cluster version detection _(backport from main)_
=> Release k8s collector `3.4.1`

.github/workflows/buildAndDeploy.yml, deploy/helm/CHANGELOG.md, deploy/helm/Chart.yaml, deploy/helm/tests/__snapshot__/logs-fargate-config-map_test.yaml.snap, deploy/helm/tests/swo-agent-statefulset_test.yaml, deploy/helm/values.yaml
Update image to [0.11.3](https://github.com/solarwinds/swi-k8s-opentelemetry-collector/releases/tag/0.11.3) and include changes from `k8s collector` [3.4.1](https://github.com/solarwinds/swi-k8s-opentelemetry-collector/releases/tag/swo-k8s-collector-3.4.1).
=> Release k8s collector 4.0.0-alpha.7

build/docker/Dockerfile.Windows-2022, build/docker/structure-test.yaml, deploy/helm/CHANGELOG.md, deploy/helm/Chart.yaml, deploy/helm/tests/__snapshot__/logs-fargate-config-map_test.yaml.snap, src/cmd/go.mod, src/cmd/go.sum, src/cmd/main.go
- Upgraded collector image to `0.10.3`
- https://github.com/solarwinds/swi-k8s-opentelemetry-collector/compare/0.10.2...0.10.3
=> Release k8s collector `3.4.2`

README.md, deploy/helm/CHANGELOG.md, deploy/helm/metrics-collector-config.yaml, deploy/helm/templates/NOTES.txt, deploy/helm/tests/__snapshot__/metrics-collector-config-map-fargate_test.yaml.snap, deploy/helm/tests/__snapshot__/metrics-collector-config-map_test.yaml.snap, deploy/helm/tests/__snapshot__/metrics-deployment_test.yaml.snap, deploy/helm/tests/metrics-deployment_test.yaml, deploy/helm/values.yaml
* Update grpcurl image from 1.8.9 to 1.9.1 for security fixes
* Update Readme to reflect the current state of the `k8s collector`
* Add a workaround for a broken metric aggregations - fix for a regression in 4.0.0-alpha.8
* Improve configuration warnings introduced in 4.0.0-alpha.8
=> General fixes after 4.0.0-alpha.8

deploy/helm/CHANGELOG.md, deploy/helm/templates/metrics-deployment.yaml, deploy/helm/templates/swo-agent-statefulset.yaml, deploy/helm/tests/metrics-deployment_test.yaml
When `otel.https_proxy_url` is set, apply it also to SWO Agent.
Additionally, disable SolarWinds Observability OTEL endpoint check init container because `grpcurl` doesn't support proxy.
=> Fix support for proxy

deploy/helm/CHANGELOG.md, deploy/helm/node-collector-config.yaml, deploy/helm/templates/node-collector-daemon-set-windows.yaml, deploy/helm/templates/node-collector-daemon-set.yaml, deploy/helm/tests/__snapshot__/node-collector-config-map-windows_test.yaml.snap, deploy/helm/tests/__snapshot__/node-collector-config-map_test.yaml.snap, deploy/helm/tests/__snapshot__/node-collector-daemon-set-windows_test.yaml.snap, deploy/helm/tests/__snapshot__/node-collector-daemon-set_test.yaml.snap, deploy/helm/tests/node-collector-config-map-windows_test.yaml
OTEL Collector [v0.101.0](https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/tag/v0.101.0) added a new `container` parser to the `filelog` receiver.
The new parser should provide a unified way for parsing container logs and metadata from them. Plus, it should be more efficient than the combination of other parsers that is used usually.
This PR replaces the old combination of parsers with the new one.
Notes:
* The new parser has some breaking changes (e.g. moving stuff from `attributes` to `resource_attributes`). So, in situations, where customers depend on the old behavior, we still deploy the original configuration. When customers use the filtering syntax (which is a breaking change by itself), or no custom filters at all, we use the new parser.
The behavior in …
=> Use `container-parser` operator in `filelogreceiver` instead of custom configuration

deploy/helm/CHANGELOG.md, deploy/helm/tests/__snapshot__/k8s-collector-deployment_test.yaml.snap, deploy/helm/tests/__snapshot__/metrics-collector-config-map-fargate_test.yaml.snap, deploy/helm/tests/__snapshot__/metrics-collector-config-map_test.yaml.snap, deploy/helm/tests/__snapshot__/reducer-deployment_test.yaml.snap, deploy/helm/tests/k8s-collector-deployment_test.yaml, deploy/helm/tests/kernel-collector-daemonset_test.yaml, deploy/helm/tests/reducer-deployment_test.yaml, deploy/helm/values.yaml
The default setting is now:
```yaml
ebpfNetworkMonitoring:
enabled: true
```
=> Enable the automatic deployment of the OTEL Network Collector to the cluster

.github/workflows/buildAndDeployHelm.yml, deploy/helm/CHANGELOG.md, deploy/helm/README.md, deploy/helm/templates/_helpers.tpl, deploy/helm/templates/asserts.yaml, deploy/helm/templates/common-env-config-map.yaml, deploy/helm/templates/logs-fargate-config-map.yaml, deploy/helm/templates/metrics-deployment.yaml, deploy/helm/templates/node-collector-daemon-set-windows.yaml, deploy/helm/templates/node-collector-daemon-set.yaml, deploy/helm/templates/swo-agent-statefulset.yaml, deploy/helm/tests/__snapshot__/logs-fargate-config-map_test.yaml.snap, deploy/helm/tests/__snapshot__/metrics-deployment_test.yaml.snap, deploy/helm/tests/__snapshot__/node-collector-daemon-set-windows_test.yaml.snap, deploy/helm/tests/__snapshot__/node-collector-daemon-set_test.yaml.snap, deploy/helm/tests/assert_test.yaml, deploy/helm/tests/logs-fargate-config-map_test.yaml, deploy/helm/tests/node-collector-daemon-set-windows_test.yaml, deploy/helm/tests/node-collector-daemon-set_test.yaml, deploy/helm/values.schema.json, deploy/helm/values.yaml
Make `cluster.uid` optional. Use `cluster.name` if `cluster.uid` is not provided. Make sure it's safe to use in a file path. And add a values check for obviously incorrect `cluster.name` and `cluster.uid` values.
There is a change in behavior of how log checkpoint folders are named. And depending on the provided `cluster.uid` value, the Fargate config can also generate a different log group name.
=> Make `cluster.uid` optional

.github/cr.sh, .github/workflows/buildAndDeploy.yml, .github/workflows/buildAndTestHelm.yml, .github/workflows/releaseHelm.yml, deploy/helm/Chart.yaml, deploy/helm/templates/autoupdate/autoupdate-cronjob.yaml, doc/development.md
After good discussion with @pstranak-sw we came out with idea to change form `create&push tag` to` create a PR with version change` which fixes several problems:
* local helm template/install for testing
* cloud extensions pipeline
* release without approval
* `git tag x.v.y`, 
* `git push origin x.z.y`
* Open PR with change to Chart.yaml
* Get it approved & merged
* Approve  & merge PR created by GH Action
Includes changes from #716 as it does not require version change in test anymore.
=> Fix service releases

deploy/helm/templates/node-collector-daemon-set-windows.yaml, deploy/helm/templates/node-collector-daemon-set.yaml, deploy/helm/tests/__snapshot__/node-collector-daemon-set-windows_test.yaml.snap, deploy/helm/tests/__snapshot__/node-collector-daemon-set_test.yaml.snap, deploy/helm/tests/node-collector-daemon-set_test.yaml
Instead of using sha256 for hostPath it now replaces invalid characters, so for standard cluster.ids it should be unchanged during upgrade. If the result is empty it will use sha256. It should be much less breaking for the customers compared to original https://github.com/solarwinds/swi-k8s-opentelemetry-collector/pull/716
=> NH-90272: Instead of using sha256 for hostPath it now replaces invalid characters

.github/cr.sh, .github/workflows/buildAndDeploy.yml, .github/workflows/buildAndTestHelm.yml, .github/workflows/releaseHelm.yml, deploy/helm/Chart.yaml
Find all commits in given PATH between two tags, and add it as release notes into release.
* Excludes merge commits
* handles changelog differently for alpha/standard releases
data source:
```
git log "swo-k8s-collector-4.0.0..swo-k8s-collector-4.1.0-alpha.4" --pretty=format:"%s" -- src build  | grep -v Merge
Bump library/golang in /build/docker
NH-90671 Bump base image
Bump distroless/static-debian12 in /build/docker
Bump debian from 12.6 to 12.7 in /build/docker
```
=> Generate changelog to release

deploy/helm/templates/events-collector-deployment.yaml, deploy/helm/templates/metrics-deployment.yaml, deploy/helm/templates/node-collector-daemon-set.yaml, deploy/helm/templates/openshift/openshift-role-binding.yaml, deploy/helm/templates/openshift/openshift-role.yaml, deploy/helm/tests/__snapshot__/events-collector-deployment_test.yaml.snap, deploy/helm/tests/__snapshot__/metrics-deployment_test.yaml.snap, deploy/helm/tests/__snapshot__/node-collector-daemon-set_test.yaml.snap, deploy/helm/values.schema.json, deploy/helm/values.yaml
Our collector should be able to run on openshift cluster. 
Limitations: 
- ebpf is not running correctly - https://github.com/open-telemetry/opentelemetry-network/issues/254
=> Adds support for RedHat OpenShift clusters

deploy/helm/CHANGELOG.md, deploy/helm/events-collector-config.yaml, deploy/helm/tests/__snapshot__/events-collector-config-map_test.yaml.snap
This PR adds labels and annotations to all the kubernetes entities.
=> Added labels and annotations to all the entities

.github/workflows/buildAndDeploy.yml, deploy/helm/templates/node-collector-daemon-set-windows.yaml, deploy/helm/tests/__snapshot__/node-collector-daemon-set-windows_test.yaml.snap, deploy/helm/tests/node-collector-daemon-set-windows_test.yaml
Artifact hub is complaining about using different tags for these images:
```
error scanning image solarwinds/swi-opentelemetry-collector:0.11.5-nanoserver: error running trivy on image solarwinds/swi-opentelemetry-collector:0.11.5-nanoserver: * remote error: no child with platform linux/amd64 in index solarwinds/swi-opentelemetry-collector:0.11.5-nanoserver (package swo-k8s-collector:4.1.0)
```
=> Build all images under one tag

.github/actions/deploy-kubernetes/action.yml
The used `k3s` stopped working, likely because the build machine switched to a newer Ubuntu release. Switching to `kind`, which we use in other places, did not work for some reason. So this PR just updates the version of the cluster and of the build action.
=> Update autoupdate test

deploy/helm/node-collector-config.yaml, deploy/helm/tests/__snapshot__/node-collector-config-map-windows_test.yaml.snap, deploy/helm/tests/__snapshot__/node-collector-config-map_test.yaml.snap
This is needed for scraping kube-controller-manager
=> Adding support to discover and scrape `https` prometheus endpoints

deploy/helm/CHANGELOG.md, deploy/helm/Chart.yaml, deploy/helm/node-collector-config.yaml, deploy/helm/tests/__snapshot__/node-collector-config-map-windows_test.yaml.snap, deploy/helm/tests/__snapshot__/node-collector-config-map_test.yaml.snap
Enable histogram metrics `k8s.etcd_disk_wal_fsync_duration_seconds` and `k8s.etcd_disk_backend_commit_duration_seconds` on node collector - discovery.
=> NH-67059 add etcd metrics

.github/add_annotation.sh, .github/cr.sh, deploy/helm/Chart.yaml
We need to add annotation to Chart.yaml instead of index.yaml of helm repo.  Adding also prerelease tag and license to improve artifacthub visualization. We can still automate versions of network collector to be pulled automatically from values.yaml.
=> Move annotations to Chart.yaml

doc/development.md, tests/deploy/base/mocks.yaml
Add a separate `http://localhost:8088/manifests.json` testing endpoint.
Update `timeseries-mock-service` to use a newer OTEL collector version.
=> Add a separate testing endpoint for manifests

deploy/helm/CHANGELOG.md, deploy/helm/metrics-collector-config.yaml, deploy/helm/node-collector-config.yaml, deploy/helm/tests/__snapshot__/metrics-collector-config-map-fargate_test.yaml.snap, deploy/helm/tests/__snapshot__/metrics-collector-config-map_test.yaml.snap, deploy/helm/tests/__snapshot__/node-collector-config-map-windows_test.yaml.snap, deploy/helm/tests/__snapshot__/node-collector-config-map_test.yaml.snap, deploy/helm/values.schema.json, deploy/helm/values.yaml, skaffold.yaml, tests/integration/expected_telemetry/deployment_with_metric.json, tests/integration/expected_telemetry/pod.json
using `otel.metrics.autodiscovery.prefix` (default `k8s.`)
* Istio metrics that are created from original ones keep `k8s.` as those metrics are required for topology view
* etcd and kube-controller-manager metrics are scraped independently on autodiscovery. 
* There is list of required metrics, that will always have `k8s.` prefix. If autodiscovery prefix differs from `k8s.` those metrics are copied.
=> Make it possible to customise prefix of discovered metrics

deploy/helm/metrics-collector-config.yaml, deploy/helm/tests/__snapshot__/metrics-collector-config-map-fargate_test.yaml.snap, deploy/helm/tests/__snapshot__/metrics-collector-config-map_test.yaml.snap
This PR enables [cert-manager](https://cert-manager.io/) metrics by default.
=> Cert-manager metrics are enabled by default

deploy/helm/Chart.yaml, deploy/helm/node-collector-config.yaml, deploy/helm/tests/__snapshot__/node-collector-config-map-windows_test.yaml.snap, deploy/helm/tests/__snapshot__/node-collector-config-map_test.yaml.snap
`{{- if .Values.otel.metrics.autodiscovery.prometheusEndpoints.enabled}}` should end before etc/controller manager
=> NH-94277: fixing scrape of etcd and controller manager with autodiscovery disabled

deploy/helm/Chart.yaml, deploy/helm/node-collector-config.yaml, deploy/helm/tests/__snapshot__/node-collector-config-map_test.yaml.snap
=> NH-94277: Fixing scraping of etcd and controller-manager when autodiscovery is disabled

deploy/helm/events-collector-config.yaml, deploy/helm/metrics-collector-config.yaml, deploy/helm/node-collector-config.yaml, deploy/helm/tests/__snapshot__/events-collector-config-map_test.yaml.snap, deploy/helm/tests/__snapshot__/metrics-collector-config-map-fargate_test.yaml.snap, deploy/helm/tests/__snapshot__/metrics-collector-config-map_test.yaml.snap, deploy/helm/tests/__snapshot__/node-collector-config-map-windows_test.yaml.snap, deploy/helm/tests/__snapshot__/node-collector-config-map_test.yaml.snap
This PR removes `name` and `version` from the scope context
*Before*
```json
{
"resourceMetrics": [
{
"resource":  ...
"scopeMetrics": [
{
"scope": {
"name": "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver",
"version": "0.11.4"
}
}
]
}
]
}
```
*After*
```json
{
"resourceMetrics": [
{
"resource":  ...
"scopeMetrics": [
{
"scope": { }
}
]
}
]
}
```
=> Removed `name` and `version` from the scope context

deploy/helm/Chart.yaml, deploy/helm/README.md, deploy/helm/values.yaml
* So that it is not needed in `Instrumentation` resource type
* Updated doc
* released as 4.3.0-alpha.3
=> Predefining Java autoinstrumentation image in operator

build/docker/Dockerfile.Windows-2022, src/cmd/go.mod, src/internal/coreinternal/go.mod, src/internal/k8sconfig/go.mod, src/processor/k8sattributesprocessor/go.mod, src/wrapper/go.mod
Update Go toolchain to 1.23. Also, use `go 1.23.0` instead of `go 1.23` in `go.mod` files, because some tooling, like our CodeQL checks, has trouble with parsing the former format.
=> Update Go to 1.23

deploy/helm/templates/node-collector-daemon-set-windows.yaml, deploy/helm/tests/__snapshot__/node-collector-daemon-set-windows_test.yaml.snap
New EKS Windows AMI templates enforce permission checks when accessing Pod logs. Unlike the Linux version of the node collector, the Windows one did not use elevated user to access them. This PR changes that.
=> Fix collecting logs on Windows

deploy/helm/Chart.yaml
Removed name and version from scope context of all messages
Updated OTEL Collector to v0.113.0
Updated base images
Fixed collecting logs on Windows
=> Release k8s collector 4.3.0-alpha.4

deploy/helm/node-collector-config.yaml, deploy/helm/tests/__snapshot__/node-collector-config-map-windows_test.yaml.snap
The `container` operator now supports Windows log paths natively.
=> Remove workaround that is no longer necessary after updating OTEL Collector to v0.113.0

deploy/helm/tests/__snapshot__/events-collector-config-map_test.yaml.snap, deploy/helm/values.yaml
The limits were set unnecessarily low, make them the same as for logs. The actual container requests/limits are unchanged.
=> Adjust memory limits in the events collector

.github/actions/deploy-kubernetes/action.yml, .github/workflows/buildAndTestHelm.yml, deploy/helm/README.md, deploy/helm/templates/asserts.yaml
* Increase required Helm version from 3.8 to 3.9.
* Explicitly mention it in the documentation.
* Check for the version during chart installation.
Note: Helm 3.9.0 is the first version where the `.Capabilities.HelmVersion.Version` actually works.
=> Require Helm 3.9.0 or newer

deploy/helm/Chart.lock, deploy/helm/Chart.yaml, deploy/helm/metrics-collector-config.yaml, deploy/helm/tests/__snapshot__/metrics-collector-config-map-fargate_test.yaml.snap, deploy/helm/tests/__snapshot__/metrics-collector-config-map_test.yaml.snap, doc/exported_metrics.md, tests/deploy/tests/test_metric_manifest.yaml, tests/integration/expected_metric_names.txt, tests/integration/expected_telemetry/service.json
The new version removes two deprecated metrics `kube_endpoint_address_not_ready` and `kube_endpoint_address_available`.
=> Update kube-state-metrics sub-chart to 5.28.0

deploy/helm/metrics-collector-config.yaml, deploy/helm/templates/_common-config.tpl, deploy/helm/tests/__snapshot__/metrics-collector-config-map-fargate_test.yaml.snap, deploy/helm/tests/__snapshot__/metrics-collector-config-map_test.yaml.snap, deploy/helm/tests/__snapshot__/node-collector-config-map-windows_test.yaml.snap, deploy/helm/tests/__snapshot__/node-collector-config-map_test.yaml.snap
This PR removes `sw.k8s.pod.status` from `metrics-collector-config.yaml`
=> Remove pod status from metrics

.github/workflows/buildAndDeploy.yml
Migrate from PAT tokens to OAT tokens.
Ticket: https://swicloud.atlassian.net/browse/ENOPS-5919
=> ENOPS-5919 - Update buildAndDeploy.yml - use OAT instead of PAT

src/processor/containerprocessor/log_constructor.go, src/processor/containerprocessor/processor.go, src/processor/containerprocessor/processor_test.go
When initial poll is being done it goes through all manifests. The timestamp was previously filled with the last change in manifest (parsed from manifest's `conditions` part) and it could have been very old change as not every manifest changes frequently.  There are some restrictions in the ingestion pipeline ignoring log records outside of accepted time interval so it was ignoring containers created from manifests that did not update lately.
PR introducing new processor including this bug: https://github.com/solarwinds/swi-k8s-opentelemetry-collector/pull/878
Timestamp of new Entity state event log is filled by timestamp of processed `logRecord` which caries `manifest` as in its body.
=> Fix timestamp of entity state events

deploy/helm/Chart.yaml
The original link goes to 404.
=> Fix "Source" link in Helm chart

deploy/helm/Chart.lock, deploy/helm/Chart.yaml, deploy/helm/charts/prometheusCRDs/Chart.yaml, deploy/helm/charts/prometheusCRDs/crds/crd-podmonitors.yaml, deploy/helm/charts/prometheusCRDs/crds/crd-probes.yaml, deploy/helm/charts/prometheusCRDs/crds/crd-scrapeconfigs.yaml, deploy/helm/charts/prometheusCRDs/crds/crd-servicemonitors.yaml, deploy/helm/templates/_helpers.tpl, deploy/helm/templates/operator/discovery-collector.yaml, deploy/helm/templates/operator/target-allocator-cluster-role-binding.yaml, deploy/helm/templates/operator/target-allocator-cluster-role.yaml, deploy/helm/templates/operator/wait-for-credmanager.yaml, deploy/helm/templates/operator/wait-for-operator.yaml, deploy/helm/templates/service-account.yaml, deploy/helm/tests/__snapshot__/discovery-collector_test.yaml.snap, deploy/helm/tests/__snapshot__/node-collector-config-map-windows_test.yaml.snap, deploy/helm/tests/__snapshot__/node-collector-config-map_test.yaml.snap, deploy/helm/tests/discovery-collector_test.yaml, deploy/helm/values.schema.json, deploy/helm/values.yaml, skaffold.yaml, src/cmd/components.go, src/cmd/go.mod, src/cmd/go.sum, tests/deploy/tests/test_metric_manifest.yaml, tests/deploy/timeseries-mock-service/templates/deployment.yaml
* Depends on https://github.com/solarwinds/swi-k8s-opentelemetry-collector/pull/919 (contains also its diff)
* Adding `crd` subchart which contains Prometheus Operator CRDs
* Adding CRDs to our heml chart recommended by [Otel Operator doc](https://github.com/open-telemetry/opentelemetry-operator/tree/main/cmd/otel-allocator):
> The easiest way to do this is to grab a copy of the individual [PodMonitor](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/charts/crds/crds/crd-podmonitors.yaml) YAML and [ServiceMonitor](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/charts/crds/crds/crd-servicemonitors.yaml) YAML custom resource definitions (CRDs) from the [Kube Prometheus Operator’s Helm …
=> Adding support for Prometheus CRDs

deploy/helm/templates/crds/crd-podmonitors.yaml, deploy/helm/templates/crds/crd-probes.yaml, deploy/helm/templates/crds/crd-scrapeconfigs.yaml, deploy/helm/templates/crds/crd-servicemonitors.yaml
CRDs when they are in `crds` folder are not deleted by the Helm. Our CRDs are in `templates` folder so they are deleted, so I added `helm.sh/resource-policy: keep` annotation on them, to make sure that they are not deleted by the chart when the chart is uninstalled (they need to be always uninstalled manually as usual CRDs)
This also fix the `skaffold dev` cleanup, because what happened is that it uninstalled `sut` chart with CRDs and other Helm charts that deployed custom resources that were based on those CRDs were in corrupted state not being able to uninstall.
=> Fixing `skaffold dev` cleanup - CRD's shouldn't be deleted by the chart

deploy/helm/metrics-collector-config.yaml, deploy/helm/templates/_common-config.tpl, deploy/helm/tests/__snapshot__/metrics-collector-config-map-fargate_test.yaml.snap, deploy/helm/tests/__snapshot__/metrics-collector-config-map_test.yaml.snap, deploy/helm/tests/__snapshot__/node-collector-config-map-windows_test.yaml.snap, deploy/helm/tests/__snapshot__/node-collector-config-map_test.yaml.snap, doc/exported_metrics.md, tests/integration/expected_metric_names.txt, tests/integration/expected_telemetry/container.json, tests/integration/expected_telemetry/pod.json
Container status is computed by processor and update is sent as event. We don't need anymore duplicate logic in metric
=> Remove metric k8s.container.status

deploy/helm/values.yaml
Upgrades the autoinstrumentation-python image to APM Python 3.5.0, released Mar 14 2025.
=> NH-103832 Upgrade to APM Python 3.5.0

deploy/helm/templates/swo-agent-statefulset.yaml, deploy/helm/tests/swo-agent-statefulset_test.yaml, deploy/helm/values.yaml
This setting ensures, that the SWO Agent will be automatically unregistered from SWO 24 hours after the `k8s collector` that owns it is uninstalled.
=> Set SWO Agent as ephemeral

deploy/helm/metrics-collector-config.yaml, deploy/helm/templates/beyla/configmap.yaml, deploy/helm/templates/beyla/daemon-set.yaml, deploy/helm/tests/__snapshot__/metrics-collector-config-map-fargate_test.yaml.snap, deploy/helm/tests/__snapshot__/metrics-collector-config-map_test.yaml.snap, deploy/helm/values.schema.json, deploy/helm/values.yaml, skaffold.yaml, tests/integration/expected_telemetry/beyla.json
* Removing SYS_ADMIN capability by default, making it possible to add that
* Stoped reusing eBPFNetwork structure of telemetry.log.level
* Disabling prometheus endpoints by default, making it possible to enable
* Making it possible to override any beyla's configuration
* Enabling beyla in development environment by default
* Adding expected metrics to integration test suite, to make sure beyla is producing both network and instrumented metrics
* Cleaning up `k8s.cluster.name` from incomming attributes, because beyla send it as empty and it would cause duplicate information as we already send it as resource attribute.
=> Adding more configuration options to beyla

deploy/helm/Chart.yaml, deploy/helm/metrics-collector-config.yaml, deploy/helm/tests/__snapshot__/metrics-collector-config-map-fargate_test.yaml.snap, deploy/helm/tests/__snapshot__/metrics-collector-config-map_test.yaml.snap
on beyla application metrics (instrumented by beyla) there is empty `k8s.cluster.name` ingested. So using `upsert` in Helm to override it.
=> NH-105498: Fixing cluster name when beyla is enabled

deploy/helm/Chart.yaml, deploy/helm/templates/beyla/configmap.yaml
Those endpoints can be optionally added via values.yaml. Releasing as `4.6.0-alpha.7`
=> Removing exposed endpoints in default beyla setup

deploy/helm/events-collector-config.yaml, deploy/helm/metrics-collector-config.yaml, deploy/helm/tests/__snapshot__/events-collector-config-map_test.yaml.snap, deploy/helm/tests/__snapshot__/metrics-collector-config-map-fargate_test.yaml.snap, deploy/helm/tests/__snapshot__/metrics-collector-config-map_test.yaml.snap
Extract most of the data from the resource manifest. Additionally collect these metrics:
* kube_cronjob_info
* kube_cronjob_created
* kube_cronjob_status_last_schedule_time
=> Collect CronJob info

deploy/helm/Chart.yaml, deploy/helm/events-collector-config.yaml, deploy/helm/tests/__snapshot__/events-collector-config-map_test.yaml.snap, deploy/helm/values.schema.json, deploy/helm/values.yaml, skaffold.yaml
* This rely on deployment of https://github.com/solarwinds/solarwinds-otel-collector-releases/pull/163 as `0.123.7` (not yet released) which will include `solarwindsentityconnector` in K8s distribution.
* Configured `solarwindsentityconnector` with keys for all existing Kubernetes entities except `KubernetesCluster`.
* Those events are ingested once per 20 minutes for each entity
* Bumping version to `4.6.0-alpha.13`
Dependencies:
=> feature: Adding keep alive events that should make sure that SWO entities are updated

deploy/helm/templates/asserts.yaml, deploy/helm/tests/assert_test.yaml
If `operator.enabled` is set to `true`, check if `certmanager.enabled` is also `true` or if there is an already running `cert-manager` in the cluster.
=> Check for cert-manager when enabling deployment of OTEL operator

deploy/helm/metrics-discovery-config.yaml, deploy/helm/node-collector-config.yaml, deploy/helm/templates/_helpers.tpl, deploy/helm/templates/operator/discovery-collector.yaml, deploy/helm/tests/__snapshot__/discovery-collector_test.yaml.snap, deploy/helm/tests/__snapshot__/metrics-discovery-config-map_test.yaml.snap, deploy/helm/tests/__snapshot__/node-collector-config-map-windows_test.yaml.snap, deploy/helm/tests/__snapshot__/node-collector-config-map_test.yaml.snap, tests/deploy/tests/templates/testResources.yaml, tests/integration/expected_telemetry/deployment_with_metric.json
* `prometheusreceiver` automatically set `job` attribute based on the `job_name` in scrape config.
* `job` is automatically converted to `service.name` by OTEL Collector and there is nothing we can do about it (https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/8060). This means that `service.name` of application metrics are usually set to `pod` as that is `job_name` for our scrape_config.
* As part of this PR I am configuring Prometheus config to set `job` from `service_name` attribute if it exists in the metric, so that `service.name` resource attribute matches to `service_name` provided by application metric.
=> NH-108743: Configuring relabel config of prometheus reciever to set `service.name`

deploy/helm/metrics-discovery-config.yaml, deploy/helm/node-collector-config.yaml, deploy/helm/templates/_common-discovery-config.tpl, deploy/helm/templates/operator/discovery-collector.yaml, deploy/helm/tests/__snapshot__/discovery-collector_test.yaml.snap, deploy/helm/tests/__snapshot__/metrics-discovery-config-map_test.yaml.snap, deploy/helm/tests/__snapshot__/node-collector-config-map-windows_test.yaml.snap, deploy/helm/tests/__snapshot__/node-collector-config-map_test.yaml.snap, doc/collectorPipeline.md
I added several pipelines to Node Collector, Metrics Discovery Collector and Discovery Collector (see `_common-discovery-config.tpl` for definitions):
* metrics/discovery-custom
* metrics/discovery-scrape (this replaces previous metrics/discovery)
* metrics/discovery-istio
* metrics/relationship-state-events-workload-workload-preparation
* metrics/relationship-state-events-workload-service-preparation
* logs/stateevents
This uses [solarwindsentityconnector](https://github.com/solarwinds/solarwinds-otel-collector-contrib/tree/main/connector/solarwindsentityconnector)
as the results there should be stream of relationship state events sent based on `istio_request_bytes_sum` metric, which should produce following relationships:
* Workload -> Workload
* Workload -> Service
=> NH-108817: Creating relationship state events from Istio metrics

deploy/helm/templates/_common-discovery-config.tpl, deploy/helm/tests/__snapshot__/discovery-collector_test.yaml.snap, deploy/helm/tests/__snapshot__/metrics-discovery-config-map_test.yaml.snap, deploy/helm/tests/__snapshot__/node-collector-config-map-windows_test.yaml.snap, deploy/helm/tests/__snapshot__/node-collector-config-map_test.yaml.snap
* SWO currently has issue during state events processing, cannot handle both types in the same messages, so we need to split them
=> NH-112478: Splitting entity state events and relationship state events into two separate pipelines

deploy/helm/events-collector-config.yaml, deploy/helm/gateway-collector-config.yaml, deploy/helm/metrics-collector-config.yaml, deploy/helm/metrics-discovery-config.yaml, deploy/helm/node-collector-config.yaml, deploy/helm/templates/NOTES.txt, deploy/helm/templates/events-collector-statefulset.yaml, deploy/helm/templates/gateway/gateway-deployment.yaml, deploy/helm/templates/metrics-deployment.yaml, deploy/helm/templates/metrics-discovery-deployment.yaml, deploy/helm/templates/node-collector-daemon-set-windows.yaml, deploy/helm/templates/node-collector-daemon-set.yaml, deploy/helm/tests/events-collector-config-map_test.yaml, deploy/helm/tests/gateway-config-map_test.yaml, deploy/helm/tests/metrics-collector-config-map_test.yaml, deploy/helm/tests/metrics-discovery-config-map_test.yaml, deploy/helm/tests/node-collector-config-map-windows_test.yaml, deploy/helm/tests/node-collector-config-map_test.yaml, deploy/helm/tests/notes_test.yaml, deploy/helm/values.schema.json, deploy/helm/values.yaml, doc/development.md
Add a new Helm chart setting for enabling `pprof` profiler on `k8s collector`'s workloads.
```yaml
diagnostics:
profiling:
enabled: true
```
When enabled, we display a warning during chart's installation/upgrade.
Depends on https://github.com/solarwinds/solarwinds-otel-collector-releases/pull/197 and release of a new image.
=> Add support for Go profiler

deploy/helm/events-collector-config.yaml, deploy/helm/tests/__snapshot__/events-collector-config-map_test.yaml.snap
If we want to filter by "source", we need to have an attribute that is present in all events, same as in the regular event namespace.
https://swicloud.atlassian.net/browse/NH-112613
=> Collect 'k8s.object.name' in manifest namespace

deploy/helm/Chart.lock, deploy/helm/Chart.yaml
Interesting changes:
* Fixed reporting `reason` in `kube_pod_status_reason`
* Removed support for ApiGroups that were deprecated years ago
* KSM Deployment can now have custom labels set via the Helm chart
* KSM no longer tries to create deprecated `PodSecurityPolicy` resources (this was complicating support for AWS/Azure extensions)
* 3rd party security fixes
=> Update `kube-state-metrics` Helm chart to 6.1

deploy/helm/Chart.yaml, deploy/helm/metrics-collector-config.yaml, deploy/helm/node-collector-config.yaml, deploy/helm/templates/_common-discovery-config.tpl, deploy/helm/templates/_helpers.tpl, deploy/helm/tests/__snapshot__/discovery-collector_test.yaml.snap, deploy/helm/tests/__snapshot__/metrics-collector-config-map-fargate_test.yaml.snap, deploy/helm/tests/__snapshot__/metrics-collector-config-map_test.yaml.snap, deploy/helm/tests/__snapshot__/metrics-discovery-config-map_test.yaml.snap, deploy/helm/tests/__snapshot__/node-collector-config-map-windows_test.yaml.snap, deploy/helm/tests/__snapshot__/node-collector-config-map_test.yaml.snap, deploy/helm/values.schema.json, deploy/helm/values.yaml
* This is the result of analysis of `heap.out` of one of our customer. It turned out that cumulativetodelta is eating huge amount of memory, probably due to leak of cardinality and that it is keeping old cardinality in memory indefinitely. This should be avoided by setting `max_staleness` - see https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/cumulativetodeltaprocessor
> max_staleness: The total time a state entry will live past the time it was last seen. Set to 0 to retain state indefinitely. Default: 0
* setting max_staleness by default to triple of scrape_interval, making it configurable.
* bumping as bugfix release as 4.7.2
=> Setting `max_staleness` property of cumulativetodelta to avoid memory leaks

deploy/helm/Chart.yaml, deploy/helm/events-collector-config.yaml, deploy/helm/templates/cluster-role.yaml
This PR allows us to watch Kustomize FluxCD CRDs needed for mapping manifests to Git repos
=> Watch Kustomize FluxCD CRDs

deploy/helm/gateway-collector-config.yaml, deploy/helm/tests/__snapshot__/gateway-config-map_test.yaml.snap
In the old code, the attributes could be set on a Resource, that could contain multiple different metrics.
=> Add `grpc`, `http` and `tcp` attributes to connections in proper resource groups
