- deploy/k8s/manifest.yaml
added all metrics that should be needed for new UI (basically followed https://swicloud.atlassian.net/wiki/spaces/NIT/pages/3234824583/Prometheus+metrics+to+support+k8s+new+UI and reviewed what are needed in new List pages)
> NH-21202: Adding new metrics

- deploy/k8s/manifest.yaml
it is related to this PR: https://github.com/solarwindscloud/entity-service-schemas/pull/418
full list of conditions; https://github.com/kubernetes/api/blob/master/apps/v1/types.go#L494
> NH-21202: Handling deployment condition

- deploy/k8s/manifest.yaml
adding `sw.k8s.log.type` attribute that indicates what is the type of the log:
* event - Kubernetes event logs
* journal - journal logs
* container - container logs
> NH-21704: Categorization of logs

- deploy/k8s/manifest.yaml
Removed metric k8s.container.ready
> NH-22548 Warning in OTEL collector logs

- deploy/k8s/manifest.yaml
full list is here: https://github.com/kubernetes/kube-state-metrics/blob/master/docs/pod-metrics.md
> NH-21206: Adding two more pod metrics that define valid node

- deploy/k8s/manifest.yaml
> NH-20832: Fixing manifest to work on environment where it can't figure out capacity

- deploy/k8s/manifest.yaml
New metrics:
-  k8s.pod.spec.cpu.requests
-  k8s.pod.spec.memory.limit
-  k8s.pod.spec.memory.requests
-  k8s.pod.spec.cpu.limit
> NH-23684: Create Pod Memory / CPU utilization metrics

- deploy/k8s/manifest.yaml
- tests/deploy/base/kustomization.yaml
- tests/deploy/base/patch-apply-env-variables.yaml
- tests/deploy/base/patch-config-maps.yaml
so that it is easier to manage
> NH-20831: Moving environment variables to config map

- deploy/k8s/manifest.yaml
Add metric:
- k8s.pod.containers.running
> NH-23683: Add pod container running metric

- .circleci/config.yml
Adding noop workflow due to https://github.com/CircleCI-Public/circleci-cli/issues/577
I will try to figure out better solution later
> NH-21761: Fixing build

- .circleci/config.yml
This removes most of the false positives
> NH-25759: Applying WhiteSource suggestions

- README.md
- deploy/helm/values.yaml
updating documentation to be more clear the filter is using AND operator for the record_attributes items (a log has to match all expressions to be included)
> updating documentation

- .github/actions/deploy-skaffold/action.yml
- .github/workflows/buildAndDeploy.yml
- build/docker/Dockerfile
- build/docker/structure-test.yaml
- build/swi-k8s-opentelemetry-collector.yaml
- skaffold.yaml
* running unit tests for custom processor as part of the image build
* adding structure test, to verify whether binaries in the image are correct
> Adding image tests

- deploy/helm/CHANGELOG.md
- deploy/helm/Chart.yaml
- deploy/helm/logs-collector-config.yaml
- deploy/helm/values.yaml
- deploy/k8s/manifest.yaml
continuing trial&error fixes, to make it working on our SSP cluster, more info at this thread: https://swicloud.slack.com/archives/C02HF9XCHB8/p1674138521607229
> Exposed some configuration of filelogreciever, Changed default value `start_at` to `end`

- deploy/helm/CHANGELOG.md
- deploy/helm/events-collector-config.yaml
> NH-26014 Kubernetes agent: Change namespace where events are sent

- deploy/helm/CHANGELOG.md
- deploy/helm/logs-collector-config.yaml
- deploy/helm/values.yaml
also default `timeout` is now set to `5s`.
> NH-31513: configuration of `file_storage` extension is now available in `values.yaml`

- .github/actions/run-integration-tests/action.yaml
- .github/workflows/buildAndDeploy.yml
- build/docker/IntegrationTest.Dockerfile
- skaffold.yaml
- tests/deploy/base/integrationTestCronJob.yaml
- tests/deploy/base/mocks.yaml
- tests/deploy/tests/integrationTestCronJob.yaml
- tests/deploy/tests/kustomization.yaml
- tests/integration/test_events_collection.py
- tests/integration/test_log_collection.py
- tests/integration/test_metric_collection.py
- tests/integration/test_utils.py
* added to integration suite tests on Events and Logs, removed those from CI bash
* refactored tests to have some common functions
* test on metrics split into two tests as logically there are two things that are asserted
> NH-31661: refactoring tests, moving them from bash to new integration suite

- deploy/helm/CHANGELOG.md
- deploy/helm/Chart.yaml
Changelog contains changes compared to previous released version
> NH-32390: Bumping version to 2.1.0

- deploy/helm/metrics-collector-config.yaml
- doc/exported_metrics.md
Add missing metric about parallelism and update readme
> NH-32170 - k8s Job metrics 

- deploy/helm/CHANGELOG.md
- deploy/helm/metrics-collector-config.yaml
Introduce internal IP attribute for node.
> NH-31472 Cluster view: Add version mismatch warning, IP and age to Node list

- doc/development.md
- skaffold.yaml
- tests/deploy/base/mocks.yaml
* Added documentation describing where developers can find exported telemetry
> Improved development workflow by exporting metrics to local prometheus

- deploy/helm/CHANGELOG.md
- deploy/helm/metrics-collector-config.yaml
Rename Pending job condition state to Active.
> Feature/nh 24517 Job list view

- build/docker/structure-test.yaml
- build/swi-k8s-opentelemetry-collector.yaml
This needs to be merged before Helm chart updates https://github.com/solarwinds/swi-k8s-opentelemetry-collector/pull/210
> NH-34013: Adding `k8sattributesprocessor` to the image

- deploy/helm/metrics-collector-config.yaml
Write job condition into datapoint attribute so that it correctly groups into resource.
> NH-24517 Job list view - table

- deploy/helm/CHANGELOG.md
`Chart.yaml` and `expected_output.json` where already update by @etichy
> Release 2.3.0-alpha.3

- deploy/helm/CHANGELOG.md
- deploy/helm/metrics-collector-config.yaml
- tests/integration/expected_output.json
Prefer scrapped attributes over server-side
> NH-33965 - Enable Honor Labels

- deploy/helm/CHANGELOG.md
- deploy/helm/Chart.yaml
- tests/integration/expected_output.json
k8s.kube_pod_status_phase should no longer be sent with 0 value
> NH-35637: Fix k8s.kube_pod_status_phase is send with value 0

- deploy/helm/CHANGELOG.md
- deploy/helm/Chart.yaml
- deploy/helm/metrics-collector-config.yaml
- doc/exported_metrics.md
- tests/integration/expected_output.json
calculate node network metrics from containers
> NH-40711 calculate node network metrics from containers

- deploy/helm/CHANGELOG.md
- deploy/helm/Chart.yaml
- tests/integration/expected_output.json
increasing collector image version to 0.7.1
> NH-43083 increasing image version

- build/docker/Dockerfile
- build/docker/structure-test.yaml
- build/swi-k8s-opentelemetry-collector.yaml
- deploy/helm/CHANGELOG.md
- deploy/helm/Chart.yaml
- tests/integration/expected_output.json
I merge master to `release/2.6.0`, there were just security fixes
> NH-45461: Applying security fixes to 2.6.0

- deploy/helm/templates/_helpers.tpl
- deploy/helm/templates/events-collector-config-map.yaml
- deploy/helm/templates/logs-collector-config-map.yaml
- deploy/helm/templates/metrics-collector-config-map.yaml
- deploy/helm/tests/__snapshot__/events-collector-config-map_test.yaml.snap
- deploy/helm/tests/__snapshot__/logs-collector-config-map_test.yaml.snap
- deploy/helm/tests/__snapshot__/metrics-collector-config-map_test.yaml.snap
- deploy/helm/tests/events-collector-config-map_test.yaml
- deploy/helm/tests/logs-collector-config-map_test.yaml
- deploy/helm/tests/metrics-collector-config-map_test.yaml
- doc/development.md
* Adding snapshot tests of config maps to make sure that changes to config map are visible in git diff
* `fromYaml | toYaml` is the way to make sure that the config map is written in readable form and is not converted to escaped/encoded form
> Adding config map tests and documentation

- deploy/helm/tests/__snapshot__/logs-collector-config-map_test.yaml.snap
There was a conflict between PRs #344 and #346.
> NH-35608: Fix tests after a2558df

- deploy/helm/CHANGELOG.md
- deploy/helm/Chart.yaml
- deploy/helm/events-collector-config.yaml
- deploy/helm/metrics-collector-config.yaml
- deploy/helm/templates/_helpers.tpl
- deploy/helm/templates/logs-fargate-config-map.yaml
- deploy/helm/tests/__snapshot__/events-collector-config-map_test.yaml.snap
- deploy/helm/tests/__snapshot__/events-collector-deployment_test.yaml.snap
- deploy/helm/tests/__snapshot__/logs-daemon-set_test.yaml.snap
- deploy/helm/tests/__snapshot__/logs-fargate-config-map_test.yaml.snap
- deploy/helm/tests/__snapshot__/metrics-collector-config-map_test.yaml.snap
- deploy/helm/tests/__snapshot__/metrics-deployment_test.yaml.snap
- tests/integration/expected_output.json
Change the target log group name to `/swo/fargate/{{ $name }}` and added additional `sw.k8s.agent.manifest.version` attribute.
> NH-53106: Change log group name and add additional attributes

- deploy/helm/CHANGELOG.md
- deploy/helm/Chart.yaml
- deploy/helm/tests/__snapshot__/logs-fargate-config-map_test.yaml.snap
- tests/integration/expected_output.json
> updating version

- build/docker/Dockerfile
- build/docker/Dockerfile.Windows
- src/wrapper/go.mod
- src/wrapper/main.go
Update of Helm chart that use the image will follow. I verified Windows build manually locally.
> NH-57813: Updating image - wrapper around otel collector that try to detect checkpoint corruption

- build/docker/Dockerfile
- build/docker/structure-test.yaml
- build/swi-k8s-opentelemetry-collector.yaml
Replaces https://github.com/solarwinds/swi-k8s-opentelemetry-collector/pull/339
> Use Debian 12 image for building

- build/docker/structure-test.yaml
- build/swi-k8s-opentelemetry-collector.yaml
This is required for eBPF, its component is emitting metrics using OTLP so we must have endpoint which will listen
> NH-63239: Adding OTLP receive to the image

- build/docker/structure-test.yaml
- build/swi-k8s-opentelemetry-collector.yaml
Followup PR depends on this: https://github.com/solarwinds/swi-k8s-opentelemetry-collector/pull/448
> NH-66305: Updating Agent image to contain components necessary for application metrics discovery

- src/processor/k8sattributesprocessor/internal/kube/client_resource.go
This is reflecting this PR to opentelemetry-collector-contrib: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/23338 (which was done for 0.80.0 release and we didn't reflect previously)
> NH-66305: Optimizing amount of stored data in k8sattributes

- skaffold.yaml
found during tips/tricks session
> Fixing test cluster profile

- .dockerignore
- deploy/helm/metrics-collector-config.yaml
- deploy/helm/node-collector-config.yaml
- deploy/helm/values.yaml
- skaffold.yaml
* Since our platform does not support working with Counters it is better to add conversion support to our agent (we will need this to monitor our own internal metrics)
* Adding also filtering option
> NH-62575: Adding possibility to filter metrics and converting metrics to rate

- deploy/helm/CHANGELOG.md
- deploy/helm/templates/metrics-deployment.yaml
- deploy/helm/templates/network/k8s-collector-deployment.yaml
- deploy/helm/templates/network/kernel-collector-daemonset.yaml
- deploy/helm/templates/network/reducer-deployment.yaml
- deploy/helm/tests/__snapshot__/k8s-collector-deployment_test.yaml.snap
- deploy/helm/tests/__snapshot__/kernel-collector-daemonset_test.yaml.snap
- deploy/helm/tests/__snapshot__/reducer-deployment_test.yaml.snap
- deploy/helm/values.yaml
* added init containers to ebpf components
* making the images configurable
* as `init_image` part of values.yaml was not released yet I updated it to be able to put more init_images
> NH-67602: Added necessary init containers making sure that all components start in the right order

- deploy/helm/CHANGELOG.md
- deploy/helm/events-collector-config.yaml
- deploy/helm/metrics-collector-config.yaml
- deploy/helm/node-collector-config.yaml
- deploy/helm/templates/events-collector-deployment.yaml
- deploy/helm/templates/metrics-deployment.yaml
- deploy/helm/templates/node-collector-daemon-set-windows.yaml
- deploy/helm/templates/node-collector-daemon-set.yaml
- deploy/helm/tests/__snapshot__/events-collector-config-map_test.yaml.snap
- deploy/helm/tests/__snapshot__/metrics-collector-config-map-fargate_test.yaml.snap
- deploy/helm/tests/__snapshot__/metrics-collector-config-map_test.yaml.snap
- deploy/helm/tests/__snapshot__/node-collector-config-map-windows_test.yaml.snap
- deploy/helm/tests/__snapshot__/node-collector-config-map_test.yaml.snap
- deploy/helm/values.yaml
- skaffold.yaml
* According to https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/9135 this should significantly reduce memory requirement
* Marking it as false by default, as we need to verify it first (I already deployed both storage and nostorage options to test cluster and observing resource usage)
> NH-67033: Introducing persistent queue

- deploy/helm/CHANGELOG.md
- deploy/helm/Chart.yaml
- deploy/helm/node-collector-config.yaml
- deploy/helm/tests/__snapshot__/logs-fargate-config-map_test.yaml.snap
- deploy/helm/tests/__snapshot__/node-collector-config-map-windows_test.yaml.snap
- deploy/helm/tests/__snapshot__/node-collector-config-map_test.yaml.snap
when defined custom it broke cAdvisor processing
> NH-67033: Fixed counterToRate conversion

- deploy/helm/templates/autoupdate/clusterrole.yaml
found by @etichy, the CI job that was supposed to find this is not working as expected...
> Fixing autoupdater

- .github/workflows/buildAndDeploy.yml
- .github/workflows/releaseHelm.yaml
- deploy/helm/CHANGELOG.md
- deploy/helm/Chart.lock
- deploy/helm/Chart.yaml
- deploy/helm/metrics-collector-config.yaml
- deploy/helm/templates/metrics-collector-env-config-map.yaml
- deploy/helm/tests/__snapshot__/logs-fargate-config-map_test.yaml.snap
- deploy/helm/tests/__snapshot__/metrics-collector-config-map-fargate_test.yaml.snap
- deploy/helm/tests/__snapshot__/metrics-collector-config-map_test.yaml.snap
- deploy/helm/values.yaml
- doc/development.md
- skaffold.yaml
- tests/integration/expected_telemetry/opencost_container.json
- tests/integration/expected_telemetry/opencost_node.json
- tests/integration/expected_telemetry/opencost_pod.json
Add opencost metrics collection, currently disabled and has to be enabled via values.yaml
> NH-64803 add opencost metrics

- .github/workflows/buildAndDeploy.yml
- deploy/helm/CHANGELOG.md
- deploy/helm/Chart.yaml
- deploy/helm/templates/autoupdate/autoupdate-cronjob.yaml
- deploy/helm/tests/__snapshot__/logs-fargate-config-map_test.yaml.snap
Since this job is installing last published Helm chart, it is temporarily disabled until we release new version which has image repo fixed
> Fixing autoupdate and bumping version to 3.1.1

- .github/workflows/buildAndDeploy.yml
* enabling test as 3.1.1 is published
* Fixing verification step so that the test is actually useful
> Enabling autoupdate test

- deploy/helm/CHANGELOG.md
- deploy/helm/metrics-collector-config.yaml
- deploy/helm/templates/network/k8s-collector-deployment.yaml
- deploy/helm/tests/__snapshot__/metrics-collector-config-map-fargate_test.yaml.snap
- deploy/helm/tests/__snapshot__/metrics-collector-config-map_test.yaml.snap
- doc/collectorPipeline.md
* Added a new document describing the existing collector pipelines
* Fixed some minor issues in the Helm chart found during the creation of the documentation
> Pipeline documentation and some fixes

- deploy/helm/CHANGELOG.md
- deploy/helm/Chart.yaml
- deploy/helm/node-collector-config.yaml
- deploy/helm/tests/__snapshot__/logs-fargate-config-map_test.yaml.snap
- deploy/helm/values.yaml
- skaffold.yaml
- tests/deploy/tests/test_metric_manifest.yaml
* making minor adjustments
* bumping also docker image
> NH-67718: Bumping version to 3.2.0-alpha.8

- deploy/helm/CHANGELOG.md
- deploy/helm/Chart.yaml
- deploy/helm/templates/events-collector-deployment.yaml
- deploy/helm/templates/metrics-deployment.yaml
- deploy/helm/templates/network/k8s-collector-deployment.yaml
- deploy/helm/templates/network/reducer-deployment.yaml
- deploy/helm/tests/__snapshot__/logs-fargate-config-map_test.yaml.snap
It happened that during upgrade we were unable to download image and due to Recreate strategy no polling was running and we were unable to determine from SWO UI why.
> revert NH-61355

- deploy/helm/CHANGELOG.md
- deploy/helm/Chart.yaml
- deploy/helm/node-collector-config.yaml
- deploy/helm/tests/__snapshot__/logs-fargate-config-map_test.yaml.snap
- deploy/helm/tests/__snapshot__/node-collector-config-map-windows_test.yaml.snap
- deploy/helm/tests/__snapshot__/node-collector-config-map_test.yaml.snap
fixing istio duration metric when extracting from histogram
> fixing istio duration metric calculation

- skaffold.yaml
- tests/deploy/base/mocks.yaml
to be able to run `skaffold dev` on Mac
> Making skaffold run locally on ARM dev machines

- deploy/helm/CHANGELOG.md
- deploy/helm/templates/NOTES.txt
- deploy/helm/tests/notes_test.yaml
- deploy/helm/values.yaml
- doc/development.md
Similar to PR #561, just showing a warning instead of an error.
> NH-73933: Show warning when a deprecated OTEL endpoint is detected in `values.yaml`

- build/docker/Dockerfile
> Fix Docker image build

- deploy/helm/CHANGELOG.md
- deploy/helm/templates/swo-agent-statefulset.yaml
- deploy/helm/values.schema.json
- deploy/helm/values.yaml
Ability to control swoagent deployment by specification nodeSelector or affinity in values.yaml
> NH-71238 - Add scheduling options for swoagent statefulset

- deploy/helm/CHANGELOG.md
- deploy/helm/metrics-collector-config.yaml
- deploy/helm/templates/_common-config.tpl
- deploy/helm/tests/__snapshot__/metrics-collector-config-map-fargate_test.yaml.snap
- deploy/helm/tests/__snapshot__/metrics-collector-config-map_test.yaml.snap
- deploy/helm/tests/__snapshot__/node-collector-config-map-windows_test.yaml.snap
- deploy/helm/tests/__snapshot__/node-collector-config-map_test.yaml.snap
fixed by creating sw.k8s.cluster.version on k8s.cluster.version metric only
> NH-72863 cluster version fix

- README.md
Updated section "Limitations" with new kubernetes versions support.
> NH-75851 Updated section "Limitations"

- deploy/helm/CHANGELOG.md
- deploy/helm/Chart.yaml
- deploy/helm/tests/__snapshot__/logs-fargate-config-map_test.yaml.snap
We are working on some improvements that might be considered breaking changes. So let's bump up the version number to 4.x.x.
> Release k8s collector 4.0.0-alpha.1

- build/docker/structure-test.yaml
- src/cmd/components.go
- src/cmd/go.mod
- src/cmd/go.sum
- src/cmd/main.go
Updating docker image version to 0.11.0
> NH-68385: Adding k8sobjectsreceiver to k8s collector docker image

- deploy/helm/CHANGELOG.md
- deploy/helm/Chart.yaml
- deploy/helm/tests/__snapshot__/logs-fargate-config-map_test.yaml.snap
- deploy/helm/tests/swo-agent-statefulset_test.yaml
- deploy/helm/values.yaml
Use the image created in PR #647, update the referenced UAMS agent and release k8s collector `3.4.0-alpha.3`.
Depends on:
> Release k8s collector 3.4.0-alpha.3

- deploy/helm/CHANGELOG.md
- deploy/helm/Chart.yaml
- deploy/helm/templates/_helpers.tpl
- deploy/helm/tests/__snapshot__/logs-fargate-config-map_test.yaml.snap
- deploy/helm/tests/__snapshot__/node-collector-config-map-windows_test.yaml.snap
- deploy/helm/tests/__snapshot__/node-collector-config-map_test.yaml.snap
- deploy/helm/values.yaml
We are changing defaults and we collect all logs now.
> NH-80888 - collect all logs by default

- deploy/helm/CHANGELOG.md
- deploy/helm/Chart.yaml
- deploy/helm/tests/__snapshot__/logs-fargate-config-map_test.yaml.snap
Release a new `k8s collector` with changes from #679.
> Release `k8s collector` `4.0.0-alpha.8`

- deploy/helm/CHANGELOG.md
- deploy/helm/Chart.yaml
- deploy/helm/tests/__snapshot__/events-collector-config-map_test.yaml.snap
- deploy/helm/tests/__snapshot__/logs-fargate-config-map_test.yaml.snap
- deploy/helm/tests/events-collector-config-map_test.yaml
- deploy/helm/values.yaml
Also enable manifest collection by default.
> Release k8s collector 4.0.0

- deploy/helm/Chart.yaml
error getting logo image https://www.solarwinds.com/favicon.ico: unexpected status code received: 403 (package: swo-k8s-collector version: 4.0.0)
artifacthub.io is not able to load icon from solarwinds.com, so moving to helm.solarwinds.com
> NH-90299 Fix icon for artifacthub

- build/docker/Dockerfile
https://scout.docker.com/reports/org/solarwinds/images/host/hub.docker.com/repo/solarwinds%2Fswi-opentelemetry-collector/tag/0.11.4/digest/sha256%3A96540bfcb2feba2dd967cb0a3f06a7ac1dc61c23bc4133ec0d5bf2dc4d329667/layers?packageName=pkg%3Agolang%2Fstdlib%401.22.6
> NH-90671 Bump base image

- README.md
- deploy/helm/README.md
Based on https://github.com/artifacthub/hub/issues/4029#issuecomment-2343838276 we need to have README.md as part of helm package.
> Move readme to helm package

- deploy/helm/templates/autoupdate/autoupdate-cronjob.yaml
Jira: https://swicloud.atlassian.net/browse/NH-81349
> NH-81349 Add node selector to autoupdate cronjob

- .github/add_annotation.sh
- .github/cr.sh
- deploy/helm/Chart.yaml
Documetation for
https://artifacthub.io/docs/topics/annotations/helm/#supported-annotations
Resulted index.yaml file:
```
apiVersion: v1
entries:
swo-k8s-collector:
- apiVersion: v2
....
version: 4.2.0-alpha.2
annotations:
artifacthub.io/images: |-
- name: ebpf-kernelCollector
image: solarwinds/opentelemetry-ebpf-kernel-collector:v0.10.2
whitelisted: true
- name: ebpf-k8sCollectorWatcher
image: solarwinds/opentelemetry-ebpf-k8s-watcher:v0.10.2
whitelisted: true
- name: ebpf-k8sCollectorRelay
image: solarwinds/opentelemetry-ebpf-k8s-relay:v0.10.2
whitelisted: true
- name: ebpf-reducer
image: solarwinds/opentelemetry-ebpf-reducer:v0.10.2
whitelisted: true
```
> Whitelist network images + release

- deploy/helm/Chart.yaml
- deploy/helm/metrics-collector-config.yaml
- deploy/helm/templates/_common-config.tpl
- deploy/helm/tests/__snapshot__/metrics-collector-config-map-fargate_test.yaml.snap
- deploy/helm/tests/__snapshot__/metrics-collector-config-map_test.yaml.snap
- deploy/helm/tests/__snapshot__/node-collector-config-map-windows_test.yaml.snap
- deploy/helm/tests/__snapshot__/node-collector-config-map_test.yaml.snap
- doc/exported_metrics.md
adding workqueue_adds_total, workqueue_depth, apiserver_request_total, apiserver_request_duration_seconds(histogram) and workqueue_queue_duration_seconds(histogram) metrics
> Adding kube-api metrics

- deploy/helm/metrics-collector-config.yaml
- deploy/helm/tests/__snapshot__/metrics-collector-config-map-fargate_test.yaml.snap
- deploy/helm/tests/__snapshot__/metrics-collector-config-map_test.yaml.snap
> adding coredns metrics

- deploy/helm/Chart.yaml
4.3.0-alpha.1 does not include operator
> Bumping version to 4.3.0-alpha.2

- deploy/helm/Chart.yaml
Updated version in `Chart.yaml`
> Updated Chart

- .github/labeler.yml
Reverts solarwinds/swi-k8s-opentelemetry-collector#815
> Revert "Update labeler.yml"

- deploy/helm/Chart.yaml
- deploy/helm/events-collector-config.yaml
- deploy/helm/tests/__snapshot__/events-collector-config-map_test.yaml.snap
getting provider information as labels for manifests
> getting provider information using new processor

- .github/workflows/buildAndDeploy.yml
(cherry picked from commit 35805a65574482605ee818057298d27ca10f76ac)
> Fix branch build

- deploy/helm/templates/NOTES.txt
- deploy/helm/tests/notes_test.yaml
- deploy/helm/values.yaml
Added warning comment to autoupdate section in values.yaml
Also added a warning to NOTES in case the autoupdate is enabled.
> Added warning if autoupdate is enabled

- deploy/helm/Chart.yaml
Release https://github.com/solarwinds/swi-k8s-opentelemetry-collector/pull/905
> Bumping image version and releasing it as new alpha

- build/docker/structure-test.yaml
- src/cmd/metadata/metadata.go
- src/receiver/k8sobjectsreceiver/receiver.go
mark first watch manifest poll after restart as sw.initial.poll = true
> mark initial manifest poll

- deploy/helm/templates/swo-agent-statefulset.yaml
- deploy/helm/tests/swo-agent-statefulset_test.yaml
- deploy/helm/values.schema.json
- deploy/helm/values.yaml
+ swo-agent can use custom serviceAccountName option
+ update swo-agent to latest v2.10.136
> Make swo-agent service account configuration

- .github/actions/run-integration-tests/action.yaml
- .github/workflows/buildAndDeploy.yml
- deploy/helm/Chart.yaml
- deploy/helm/templates/swo-agent-statefulset.yaml
- deploy/helm/tests/swo-agent-statefulset_test.yaml
- deploy/helm/values.schema.json
- deploy/helm/values.yaml
* Update SWO Agent
* Make SWO Agent's service account configurable
* Update build pipeline
All changes are cherry-picked from main.
> Release Helm chart 4.3.3

- deploy/helm/Chart.yaml
- deploy/helm/templates/events-collector-statefulset.yaml
- deploy/helm/tests/__snapshot__/events-collector-statefulset_test.yaml.snap
- deploy/helm/tests/events-collector-statefulset_test.yaml
changing events deployment to statefulset
> changing events deployment to statefulset

- deploy/helm/tests/notes_test.yaml
My bad, the typo is from my PR, this one fixes it.
> Small fix of autoupdate notes-test description

- README.md
- deploy/helm/Chart.yaml
- doc/development.md
Bumping version to 4.5.0-alpha.1
> Updating documentation after removing docker image of the repository

- deploy/helm/Chart.yaml
- doc/development.md
This PR prepares release 4.5.0-alpha.5
> Release 4.5.0-alpha.5

- deploy/helm/values.yaml
> NH-105552 Upgrade to APM Python 3.6.0

- deploy/helm/templates/NOTES.txt
- deploy/helm/templates/beyla/cluster-role-binding.yaml
- deploy/helm/templates/beyla/cluster-role.yaml
- deploy/helm/templates/beyla/configmap.yaml
- deploy/helm/templates/beyla/daemon-set.yaml
- deploy/helm/values.schema.json
- deploy/helm/values.yaml
* it is opt-in using `beyla.enable`
* it does not reference subchart, I added beyla's resources directly to our chart, so that we don't need to configure it through default values.yaml
> adding Beyla as optional part of the chart

- deploy/helm/README.md
* Adding detailed feature description
* Adding mermaid diagrams
> Improving documentation

- .github/workflows/buildAndDeploy.yml
- .gitmodules
- doc/development.md
- skaffold.yaml
skaffold will use existing otel collector image by default
> Do not rebuild image by default

- .github/workflows/buildAndDeploy.yml
- doc/development.md
- skaffold.yaml
- tests/deploy/tests/values.yaml
- tests/deploy/timeseries-mock-service-custom-resources/templates/podmonitor.yaml
- tests/deploy/timeseries-mock-service-custom-resources/values.yaml
* Cleaning up Helm values
* Adding profiles that allow opt-in/opt-out features
* Updating development documentation
> Improving skaffold development workflow

- deploy/helm/values.yaml
Upgrade to APM Python 4.0.0, released Apr 29 2025
> NH-107046 Upgrade APM Python 4.0.0

- deploy/helm/metrics-collector-config.yaml
- deploy/helm/tests/__snapshot__/metrics-collector-config-map-fargate_test.yaml.snap
- deploy/helm/tests/__snapshot__/metrics-collector-config-map_test.yaml.snap
This PR implements collecting `kube_configmap_created`
> Collect kube_configmap_created

- deploy/helm/Chart.yaml
- deploy/helm/tests/swo-agent-statefulset_test.yaml
- deploy/helm/values.yaml
Updating used container images
> Release k8s collector 4.5.1

- deploy/helm/templates/metrics-discovery-deployment.yaml
- deploy/helm/tests/__snapshot__/metrics-discovery-deployment_test.yaml.snap
This was broken in a4aed4063ce40912a6cf960e80e52440e225316b
> Fix broken connection check

- deploy/helm/values.yaml
Upgrade to APM Python 4.1.0, released May 21 2025.
> NH-111011 Upgrade to APM Python 4.1.0

- deploy/helm/Chart.yaml
This branch is release candidate for 4.7.0-alpha.6
> Bumping version to 4.7.0-alpha.6

- deploy/helm/Chart.yaml
> NH-111505: Bumping version to 4.7.0

- deploy/helm/events-collector-config.yaml
- deploy/helm/gateway-collector-config.yaml
- deploy/helm/metrics-collector-config.yaml
- deploy/helm/metrics-discovery-config.yaml
- deploy/helm/node-collector-config.yaml
- deploy/helm/templates/_common-discovery-config.tpl
- deploy/helm/templates/gateway/gateway-config-map.yaml
- deploy/helm/templates/operator/discovery-collector.yaml
- deploy/helm/tests/__snapshot__/gateway-config-map_test.yaml.snap
reformatting pipelines definitions to more readable format: receivers, processors, exporters
> Reformatting pipelines definitions

- deploy/helm/gateway-collector-config.yaml
- deploy/helm/templates/_common-discovery-config.tpl
- deploy/helm/tests/__snapshot__/discovery-collector_test.yaml.snap
- deploy/helm/tests/__snapshot__/gateway-config-map_test.yaml.snap
- deploy/helm/tests/__snapshot__/metrics-discovery-config-map_test.yaml.snap
- deploy/helm/tests/__snapshot__/node-collector-config-map-windows_test.yaml.snap
- deploy/helm/tests/__snapshot__/node-collector-config-map_test.yaml.snap
- doc/collectorPipeline.md
- adding entity key attributes to beyla and istio metrics
- create relationship logs from all istio metrics
- add `beyla` and `istio` attributes to relationship logs
- updating pipeline chart
> adding key attributes to beyla and istio metrics

- deploy/helm/values.yaml
Upgrade to APM Python 4.2.0, released Jul 15 2025.
> NH-112563 Upgrade APM Python 4.2.0

- deploy/helm/Chart.yaml
- deploy/helm/events-collector-config.yaml
- deploy/helm/gateway-collector-config.yaml
- deploy/helm/metrics-collector-config.yaml
- deploy/helm/metrics-discovery-config.yaml
- deploy/helm/node-collector-config.yaml
- deploy/helm/templates/NOTES.txt
- deploy/helm/templates/_common-discovery-config.tpl
- deploy/helm/templates/events-collector-statefulset.yaml
- deploy/helm/templates/gateway/gateway-deployment.yaml
- deploy/helm/templates/metrics-deployment.yaml
- deploy/helm/templates/metrics-discovery-deployment.yaml
- deploy/helm/templates/node-collector-daemon-set-windows.yaml
- deploy/helm/templates/node-collector-daemon-set.yaml
- deploy/helm/tests/__snapshot__/discovery-collector_test.yaml.snap
- deploy/helm/tests/__snapshot__/events-collector-config-map_test.yaml.snap
- deploy/helm/tests/__snapshot__/metrics-discovery-config-map_test.yaml.snap
- deploy/helm/tests/__snapshot__/node-collector-config-map-windows_test.yaml.snap
- deploy/helm/tests/__snapshot__/node-collector-config-map_test.yaml.snap
- deploy/helm/tests/events-collector-config-map_test.yaml
- deploy/helm/tests/gateway-config-map_test.yaml
- deploy/helm/tests/metrics-collector-config-map_test.yaml
- deploy/helm/tests/metrics-discovery-config-map_test.yaml
- deploy/helm/tests/node-collector-config-map-windows_test.yaml
- deploy/helm/tests/node-collector-config-map_test.yaml
- deploy/helm/tests/notes_test.yaml
- deploy/helm/values.schema.json
- deploy/helm/values.yaml
- doc/development.md
Backporting changes from main:
* https://github.com/solarwinds/swi-k8s-opentelemetry-collector/pull/1064
* https://github.com/solarwinds/swi-k8s-opentelemetry-collector/pull/1067
* https://github.com/solarwinds/swi-k8s-opentelemetry-collector/pull/1077
* https://github.com/solarwinds/swi-k8s-opentelemetry-collector/pull/1081
> Release 4.7.1

- deploy/helm/gateway-collector-config.yaml
- deploy/helm/templates/_common-discovery-config.tpl
- deploy/helm/tests/__snapshot__/discovery-collector_test.yaml.snap
- deploy/helm/tests/__snapshot__/gateway-config-map_test.yaml.snap
- deploy/helm/tests/__snapshot__/metrics-discovery-config-map_test.yaml.snap
- deploy/helm/tests/__snapshot__/node-collector-config-map-windows_test.yaml.snap
- deploy/helm/tests/__snapshot__/node-collector-config-map_test.yaml.snap
- doc/collectorPipeline.md
- adding communication types to event
- update pipeline chart
> add communication types to events

- deploy/helm/Chart.yaml
- deploy/helm/templates/NOTES.txt
- deploy/helm/values.yaml
- doc/development.md
- skaffold.yaml
> Enabling beyla by default, disabling ebpfNetworkMonitoring by default

- deploy/helm/events-collector-config.yaml
- deploy/helm/gateway-collector-config.yaml
- deploy/helm/metrics-collector-config.yaml
- deploy/helm/metrics-discovery-config.yaml
- deploy/helm/node-collector-config.yaml
- deploy/helm/templates/operator/discovery-collector.yaml
- deploy/helm/tests/__snapshot__/discovery-collector_test.yaml.snap
- deploy/helm/tests/__snapshot__/events-collector-config-map_test.yaml.snap
- deploy/helm/tests/__snapshot__/gateway-config-map_test.yaml.snap
- deploy/helm/tests/__snapshot__/metrics-collector-config-map-fargate_test.yaml.snap
- deploy/helm/tests/__snapshot__/metrics-collector-config-map_test.yaml.snap
- deploy/helm/tests/__snapshot__/metrics-discovery-config-map_test.yaml.snap
- deploy/helm/tests/__snapshot__/node-collector-config-map-windows_test.yaml.snap
- deploy/helm/tests/__snapshot__/node-collector-config-map_test.yaml.snap
adopt format required by https://swicloud.atlassian.net/wiki/spaces/SP/pages/5509939284/TIP-67+Telemetry+Names+Registry
relevant platform code: https://github.com/solarwinds-cloud/platform-ingestion/blob/365b5012f78bdeea1538377f8bd8b6696ebda08e/chainsaw-collector/src/main/kotlin/cloud/solarwinds/chainsaw/collector/util/TelemetryNamesRegistryUtil.kt#L3
> Sender authorization update

- .github/workflows/buildAndDeploy.yml
- .github/workflows/buildAndTestHelm.yml
- deploy/helm/templates/beyla/configmap.yaml
- deploy/helm/templates/beyla/daemon-set.yaml
- deploy/helm/values.schema.json
- deploy/helm/values.yaml
Use default security permissions from its Helm chart
> Update Beyla to 2.7.0
